In [2]:
import pandas as pd

In [3]:
dfs = []
path_template = '../data/dbptm/active_result'
for i in range(3):
    dfs.append(pd.read_csv(f'{path_template}_{i}.tsv', sep='\t'))

total = pd.concat(dfs)
total

,From,Entry,Reviewed,Entry Name,Protein names,Gene Names,Organism,Length,Sequence,Alternative sequence
0,A0A021WW64,A0A021WW64,unreviewed,A0A021WW64_DROME,"Uncharacterized protein, isoform G",FBgn0058460 anon-20Ea CG40460 Dmel\CG17162 CG1...,Drosophila melanogaster (Fruit fly),274,MVVAVVAADVVERNSSRSGIDESSGFAVSPSFVGSTPDSVVKSNYT...,NaN
1,A0A023GPV6,A0A023GPV6,unreviewed,A0A023GPV6_DROME,"Uncharacterized protein, isoform J (EC 3.1.3.-...",Dmel\CG3632 MTMR3/4 CG3632 Dmel_CG3632,Drosophila melanogaster (Fruit fly),1119,MSDGSPPPSICFIRAAESYPKSQMEKEDSQLFVPFQELAGESIKYL...,NaN
2,A0A023GRW3,A0A023GRW3,unreviewed,A0A023GRW3_DROME,"Uncharacterized protein, isoform D",Dmel\CG4896 cg4896 CG4896 Dmel_CG4896,Drosophila melanogaster (Fruit fly),949,MDSRYGHSFSGGNGNGSESGYRRYSRSRSRSRERSRDRNEYRRRNS...,NaN
3,A0A023PXF8,A0A023PXF8,reviewed,YI066_YEAST,Putative uncharacterized membrane protein YIL0...,YIL066W-A,Saccharomyces cerevisiae (strain ATCC 204508 /...,147,MRIQKQQYTISSNSRINLLGILVLNVVCGKSSIFFSHPQRLGKLGG...,NaN
4,A0A023PZB3,A0A023PZB3,reviewed,FMP49_YEAST,"Protein FMP49, mitochondrial (Found in mitocho...",FMP49 YER038W-A,Saccharomyces cerevisiae (strain ATCC 204508 /...,126,MYYFSRVAARTFCCCIFFCLATAYSRPDRNPRKIEKKDKKFFGASK...,NaN
...,...,...,...,...,...,...,...,...,...,...
20152,Z4YLR9,Z4YLR9,unreviewed,Z4YLR9_MOUSE,Solute carrier family 25 (mitochondrial carrie...,Slc25a25,Mus musculus (Mouse),263,MTGSPKLFPSPGKVYLDIIFALQKEQKRSQVFDLPPAEKIVQAGDK...,NaN
20153,Z4YM84,Z4YM84,unreviewed,Z4YM84_MOUSE,Acyl-CoA-binding domain-containing protein 5,Acbd5,Mus musculus (Mouse),484,MADTPSVYETRFEAAVKVIQSLPKNGSFQPTNEMMLKFYSFYKQAT...,NaN
20154,Z4YMB8,Z4YMB8,unreviewed,Z4YMB8_MOUSE,Sperm associated antigen 9,Spag9,Mus musculus (Mouse),901,LIAKVDELTCEKDVLQGELEAVKQAKLKLEDKNRELEEELRKARAE...,NaN
20155,Z4YN06,Z4YN06,unreviewed,Z4YN06_MOUSE,Acyl-Coenzyme A binding domain containing 5,Acbd5,Mus musculus (Mouse),52,MADTPSVYETRFEAAVKVIQSLPKNGSFQPTNEMMLKFYSFYKQAT...,NaN
20156,Z4YN62,Z4YN62,unreviewed,Z4YN62_MOUSE,Ataxin 7-like 3,Atxn7l3,Mus musculus (Mouse),350,EMSLSGLDNSKLEAIAQEIYADLVEDSCLGFCFEVHRAVKCGYFFL...,NaN

In [4]:
total.to_csv('../data/dbptm/active_proteins.tsv', sep='\t')

In [5]:
total[total['Reviewed'] == 'reviewed']

,From,Entry,Reviewed,Entry Name,Protein names,Gene Names,Organism,Length,Sequence,Alternative sequence
3,A0A023PXF8,A0A023PXF8,reviewed,YI066_YEAST,Putative uncharacterized membrane protein YIL0...,YIL066W-A,Saccharomyces cerevisiae (strain ATCC 204508 /...,147,MRIQKQQYTISSNSRINLLGILVLNVVCGKSSIFFSHPQRLGKLGG...,NaN
4,A0A023PZB3,A0A023PZB3,reviewed,FMP49_YEAST,"Protein FMP49, mitochondrial (Found in mitocho...",FMP49 YER038W-A,Saccharomyces cerevisiae (strain ATCC 204508 /...,126,MYYFSRVAARTFCCCIFFCLATAYSRPDRNPRKIEKKDKKFFGASK...,NaN
5,A0A023PZF3,A0A023PZF3,reviewed,YI070_YEAST,Putative uncharacterized protein YIL071W-A,YIL071W-A,Saccharomyces cerevisiae (strain ATCC 204508 /...,158,MNNKVTLLPPRVFFCLSWSVMVNIDRRKSDRSVNLDDQHSNKPPSE...,NaN
6,A0A023PZG4,A0A023PZG4,reviewed,YL236_YEAST,Uncharacterized protein YLR236C,YLR236C,Saccharomyces cerevisiae (strain ATCC 204508 /...,107,MHTICLRSPIDESSPLPYKSIRQPLENAHSCQALCSLMAVLCASAA...,NaN
20,A0A024R1R8,A0A024R1R8,reviewed,TMA7B_HUMAN,Translation machinery-associated protein 7B,TMA7B,Homo sapiens (Human),64,MSSHEGGKKKALKQPKKQAKEMDEEEKAFKQKQKEEQKKLEVLKAK...,NaN
...,...,...,...,...,...,...,...,...,...,...
20089,Q9VSU8,X2JAU8,reviewed,NWK_DROME,Protein nervous wreck (Nwk),nwk CG43479,Drosophila melanogaster (Fruit fly),1075,MQPPPRKGNYVKFLKNLHTEQVAKLQLKNQHECDLLEDIRQFTIKR...,"VAR_SEQ 611..633; /note=""Missing (in isoform 3..."
20118,X5HYT8,X5HYT8,reviewed,SMOS1_ORYSJ,AP2-like ethylene-responsive transcription fac...,SMOS1 RLA1 Os05g0389000 LOC_Os05g32270 OSJNBa0...,Oryza sativa subsp. japonica (Rice),425,MASPGPAAGMQQKLEAAAAAAGGGDGAEWGRGMQKMEAVGAGGEGV...,NaN
20120,X5JA13,X5JA13,reviewed,SECAA_ARATH,Exocyst complex component SEC10a (AtSec10a) (E...,SEC10a At5g12370 T2L20.2,Arabidopsis thaliana (Mouse-ear cress),825,MTEGIRARGPRSSSVNSVPLILDIEDFKGDFSFDALFGNLVNDLLP...,NaN
20121,X5JB51,X5JB51,reviewed,SECAB_ARATH,Exocyst complex component SEC10b (AtSec10b),SEC10b At5g12365,Arabidopsis thaliana (Mouse-ear cress),829,MTERIRARGPRSSSVNSVPLILDIEDFKGDFSFDALFGNLVNDLLP...,NaN
20133,X6R8D5,X6R8D5,reviewed,CMIP3_HUMAN,Ciliary microtubule inner protein 3 (GUCA1A ne...,CIMIP3 GUCA1ANB,Homo sapiens (Human),112,MCKDSQKPSVPSHGPKTPSCKGVKAPHSSRPRAWKQDLEQSLAAAY...,"VAR_SEQ 1..3; /note=""MCK -> MGRKEHESPSQPHMCGWE..."

In [6]:
total[total['Reviewed'] == 'reviewed'].to_csv('../data/dbptm/active_reviewed_proteins.tsv', sep='\t')

In [7]:
phospho_path = '../data/dbptm/Phosphorylation'
phospho_data = pd.read_csv(phospho_path, sep='\t', names=['name', 'id', 'phos_index', 'ptm_type', 'pubmed_ids', 'seq_window'])
phospho_data

,name,id,phos_index,ptm_type,pubmed_ids,seq_window
0,MYSC_ACACA,P10569,311,Phosphorylation,2530230,TTGEQGRGRSSVYSCPQDPLG
1,MYSB_ACACA,P19706,315,Phosphorylation,2530230,NTGGAGAKKMSTYNVPQNVEQ
2,14333_ARATH,P42644,162,Phosphorylation,30395287;22092075;25561503,VAYKSASDIATAELAPTHPIR
3,14333_ARATH,P42644,238,Phosphorylation,30291188;24924143;30395287;19880383;20466843;2...,DNLTLWTSDMTDEAGDEIKEA
4,14335_ARATH,P42645,267,Phosphorylation,30291188;23776212;19376835;27531888;30395287;2...,KVDEQAQPPPSQ---------
...,...,...,...,...,...,...
1615049,ZRAB2_HUMAN,O95218-2,120,Phosphorylation,18669648,ENVEYIEREESDGEYDEFGRK
1615050,ZRAB2_HUMAN,O95218-2,153,Phosphorylation,18669648,SILKEVEDKESEGEEEDEDED
1615051,ZRAB2_HUMAN,O95218-2,181,Phosphorylation,18669648,EDEDEDDADLSKYNLDASEEE
1615052,ZRAB2_HUMAN,O95218-2,183,Phosphorylation,18669648,EDEDDADLSKYNLDASEEEDS
1615053,ZRAB2_HUMAN,O95218-2,188,Phosphorylation,18669648,ADLSKYNLDASEEEDSNKKKS

In [8]:
reviewed = total[total['Reviewed'] == 'reviewed']

In [9]:
grouped = phospho_data[['id', 'phos_index', 'seq_window']].groupby('id')

In [10]:
grouped_phos_data = grouped.agg(list)

In [11]:
joined = reviewed.set_index('From').join(grouped_phos_data, how='left')
joined

,Entry,Reviewed,Entry Name,Protein names,Gene Names,Organism,Length,Sequence,Alternative sequence,phos_index,seq_window
From,,,,,,,,,,,
A0A023PXF8,A0A023PXF8,reviewed,YI066_YEAST,Putative uncharacterized membrane protein YIL0...,YIL066W-A,Saccharomyces cerevisiae (strain ATCC 204508 /...,147,MRIQKQQYTISSNSRINLLGILVLNVVCGKSSIFFSHPQRLGKLGG...,NaN,"[113, 119]","[TRCCPSQSLETPGSVASHVVL, QSLETPGSVASHVVLALSSKC]"
A0A023PZB3,A0A023PZB3,reviewed,FMP49_YEAST,"Protein FMP49, mitochondrial (Found in mitocho...",FMP49 YER038W-A,Saccharomyces cerevisiae (strain ATCC 204508 /...,126,MYYFSRVAARTFCCCIFFCLATAYSRPDRNPRKIEKKDKKFFGASK...,NaN,[71],[PTIEYVVEEVTRTHQPEQYDI]
A0A023PZF3,A0A023PZF3,reviewed,YI070_YEAST,Putative uncharacterized protein YIL071W-A,YIL071W-A,Saccharomyces cerevisiae (strain ATCC 204508 /...,158,MNNKVTLLPPRVFFCLSWSVMVNIDRRKSDRSVNLDDQHSNKPPSE...,NaN,[145],[CPDIINFVNSSLISSKSIPSV]
A0A023PZG4,A0A023PZG4,reviewed,YL236_YEAST,Uncharacterized protein YLR236C,YLR236C,Saccharomyces cerevisiae (strain ATCC 204508 /...,107,MHTICLRSPIDESSPLPYKSIRQPLENAHSCQALCSLMAVLCASAA...,NaN,"[14, 18]","[ICLRSPIDESSPLPYKSIRQP, SPIDESSPLPYKSIRQPLENA]"
A0A024R1R8,A0A024R1R8,reviewed,TMA7B_HUMAN,Translation machinery-associated protein 7B,TMA7B,Homo sapiens (Human),64,MSSHEGGKKKALKQPKKQAKEMDEEEKAFKQKQKEEQKKLEVLKAK...,NaN,"[55, 61]","[AKVVGKGPLATGGIKKSGKK-, GPLATGGIKKSGKK-------]"
...,...,...,...,...,...,...,...,...,...,...,...
Q9VSU8,X2JAU8,reviewed,NWK_DROME,Protein nervous wreck (Nwk),nwk CG43479,Drosophila melanogaster (Fruit fly),1075,MQPPPRKGNYVKFLKNLHTEQVAKLQLKNQHECDLLEDIRQFTIKR...,"VAR_SEQ 611..633; /note=""Missing (in isoform 3...",[1047],[APKQVVGGRASIPEELDSNQL]
X5HYT8,X5HYT8,reviewed,SMOS1_ORYSJ,AP2-like ethylene-responsive transcription fac...,SMOS1 RLA1 Os05g0389000 LOC_Os05g32270 OSJNBa0...,Oryza sativa subsp. japonica (Rice),425,MASPGPAAGMQQKLEAAAAAAGGGDGAEWGRGMQKMEAVGAGGEGV...,NaN,"[338, 343, 347]","[SKEMDEGKTVTPVPATGHDTT, EGKTVTPVPATGHDTTAVNMN,..."
X5JA13,X5JA13,reviewed,SECAA_ARATH,Exocyst complex component SEC10a (AtSec10a) (E...,SEC10a At5g12370 T2L20.2,Arabidopsis thaliana (Mouse-ear cress),825,MTEGIRARGPRSSSVNSVPLILDIEDFKGDFSFDALFGNLVNDLLP...,NaN,"[12, 13, 133, 14, 17, 241, 326, 329, 331, 477,...","[TEGIRARGPRSSSVNSVPLIL, EGIRARGPRSSSVNSVPLILD,..."
X5JB51,X5JB51,reviewed,SECAB_ARATH,Exocyst complex component SEC10b (AtSec10b),SEC10b At5g12365,Arabidopsis thaliana (Mouse-ear cress),829,MTERIRARGPRSSSVNSVPLILDIEDFKGDFSFDALFGNLVNDLLP...,NaN,"[12, 13, 133, 14, 17, 326, 329, 331, 477, 478,...","[TERIRARGPRSSSVNSVPLIL, ERIRARGPRSSSVNSVPLILD,..."
X6R8D5,X6R8D5,reviewed,CMIP3_HUMAN,Ciliary microtubule inner protein 3 (GUCA1A ne...,CIMIP3 GUCA1ANB,Homo sapiens (Human),112,MCKDSQKPSVPSHGPKTPSCKGVKAPHSSRPRAWKQDLEQSLAAAY...,"VAR_SEQ 1..3; /note=""MCK -> MGRKEHESPSQPHMCGWE...","[24, 27, 34, 56]","[MCGWEDSQKPSVPSHGPKTPS, WEDSQKPSVPSHGPKTPSCKG,..."

# Verify sequence matches

In [27]:
def verify_sequence_windows(row, radius=10):
    """
    Checks if all windows in a row correctly match the sequence at given indices.
    Assumes 0-based indexing.
    """
    seq = row['Sequence']
    indices = row['phos_index']
    windows = row['seq_window']
    seq_len = len(seq)

    # zip allows us to iterate through indices and windows simultaneously
    for idx, provided_window in zip(indices, windows):
        # 1. Define the theoretical boundaries
        # Indices are 1-based
        start = int(idx) -1 - radius
        end = int(idx) + radius  # +1 because Python slicing is exclusive at the end

        # 2. Extract the valid part of the sequence (clamped to 0 and seq_len)
        valid_start = max(0, start)
        valid_end = min(seq_len, end)
        actual_fragment = seq[valid_start:valid_end]

        # 3. Calculate how much padding is needed
        pre_padding = "-" * max(0, -start)
        post_padding = "-" * max(0, end - seq_len)

        # 4. Reconstruct the expected window
        expected_window = pre_padding + actual_fragment + post_padding

        # 5. Compare
        if expected_window != provided_window:
            return False # Return False as soon as one window doesn't match
            
    return True # All windows matched

In [28]:
match_mask = joined.apply(verify_sequence_windows, axis=1)
match_mask.sum()

60176

In [29]:
filtered = joined[match_mask]

In [30]:
info = filtered[['Entry', 'phos_index', 'Sequence',]].reset_index(drop=True).rename(columns={'Entry' : 'id', 'phos_index' : 'sites', 'Sequence' : 'sequence'})

In [31]:
info

,id,sites,sequence
0,A0A023PXF8,"[113, 119]",MRIQKQQYTISSNSRINLLGILVLNVVCGKSSIFFSHPQRLGKLGG...
1,A0A023PZB3,[71],MYYFSRVAARTFCCCIFFCLATAYSRPDRNPRKIEKKDKKFFGASK...
2,A0A023PZF3,[145],MNNKVTLLPPRVFFCLSWSVMVNIDRRKSDRSVNLDDQHSNKPPSE...
3,A0A023PZG4,"[14, 18]",MHTICLRSPIDESSPLPYKSIRQPLENAHSCQALCSLMAVLCASAA...
4,A0A024R1R8,"[55, 61]",MSSHEGGKKKALKQPKKQAKEMDEEEKAFKQKQKEEQKKLEVLKAK...
...,...,...,...
60171,X1WGV5,"[37, 39, 43, 44, 50, 52]",MMIDDFETHAARSSGDLWSEVCSSLPEPREQHGGQFTDSFEPSSPG...
60172,X2JAU8,[1047],MQPPPRKGNYVKFLKNLHTEQVAKLQLKNQHECDLLEDIRQFTIKR...
60173,X5HYT8,"[338, 343, 347]",MASPGPAAGMQQKLEAAAAAAGGGDGAEWGRGMQKMEAVGAGGEGV...
60174,X5JA13,"[12, 13, 133, 14, 17, 241, 326, 329, 331, 477,...",MTEGIRARGPRSSSVNSVPLILDIEDFKGDFSFDALFGNLVNDLLP...
60175,X5JB51,"[12, 13, 133, 14, 17, 326, 329, 331, 477, 478,...",MTERIRARGPRSSSVNSVPLILDIEDFKGDFSFDALFGNLVNDLLP...

In [32]:
info

,id,sites,sequence
0,A0A023PXF8,"[113, 119]",MRIQKQQYTISSNSRINLLGILVLNVVCGKSSIFFSHPQRLGKLGG...
1,A0A023PZB3,[71],MYYFSRVAARTFCCCIFFCLATAYSRPDRNPRKIEKKDKKFFGASK...
2,A0A023PZF3,[145],MNNKVTLLPPRVFFCLSWSVMVNIDRRKSDRSVNLDDQHSNKPPSE...
3,A0A023PZG4,"[14, 18]",MHTICLRSPIDESSPLPYKSIRQPLENAHSCQALCSLMAVLCASAA...
4,A0A024R1R8,"[55, 61]",MSSHEGGKKKALKQPKKQAKEMDEEEKAFKQKQKEEQKKLEVLKAK...
...,...,...,...
60171,X1WGV5,"[37, 39, 43, 44, 50, 52]",MMIDDFETHAARSSGDLWSEVCSSLPEPREQHGGQFTDSFEPSSPG...
60172,X2JAU8,[1047],MQPPPRKGNYVKFLKNLHTEQVAKLQLKNQHECDLLEDIRQFTIKR...
60173,X5HYT8,"[338, 343, 347]",MASPGPAAGMQQKLEAAAAAAGGGDGAEWGRGMQKMEAVGAGGEGV...
60174,X5JA13,"[12, 13, 133, 14, 17, 241, 326, 329, 331, 477,...",MTEGIRARGPRSSSVNSVPLILDIEDFKGDFSFDALFGNLVNDLLP...
60175,X5JB51,"[12, 13, 133, 14, 17, 326, 329, 331, 477, 478,...",MTERIRARGPRSSSVNSVPLILDIEDFKGDFSFDALFGNLVNDLLP...

In [33]:
info[info.apply(lambda row: any([int(i) - 1 > len(row['sequence']) for i in row['sites']]), axis=1)]

Empty DataFrame
Columns: [id, sites, sequence]
Index: []

In [34]:
info.to_json('../data/dbptm/dbptm_info.json', indent=4)