In [1]:
import pandas as pd

In [2]:
path = '../data/deepmvp/phos_st_testing_70.tsv'

In [3]:
df = pd.read_csv(path, sep='\t')

In [4]:
df

      protein aa   pos                                                  x  y
0      Q9BYE2  S    10  XXXXXXXXXXXXXXXXXXXXXMERDSHGNASPARTPSAGASPAQAS...  1
1      Q9BYE2  S    20  XXXXXXXXXXXMERDSHGNASPARTPSAGASPAQASPAGTPPGRAS...  1
2      Q9BYE2  S    25  XXXXXXMERDSHGNASPARTPSAGASPAQASPAGTPPGRASPAQAS...  1
3      Q9BYE2  T    29  XXMERDSHGNASPARTPSAGASPAQASPAGTPPGRASPAQASPAQA...  1
4      Q9BYE2  S    35  SHGNASPARTPSAGASPAQASPAGTPPGRASPAQASPAQASPAGTP...  1
...       ... ..   ...                                                ... ..
56687  Q7Z7G8  S  1473  HQQHGFLSLTYTKAVTKNVRHKLTSRNERRSFHKLSEGLMDGSPHF...  0
56688  Q5JV73  S    79  AEILRQVTVHRDPIYGFGFVAGSERPVVVRSVRPGGPSENKLLAGD...  0
56689  Q8N8S7  S    29  XXMSEQSICQARAAVMVYDDANKKWVPAGGSTGFSRVHIYHHTGNN...  0
56690  O75912  S   132  ALDEPAAAGQKEKDEALEEKLRNLTFRKQVSYRKAISRAGLQHLAP...  0
56691  Q6ZN55  S   320  GRRARRNNSGEAGGAATQELFCSACDQLFLSPHQLQQHLRSHREGV...  0

[56692 rows x 5 columns]

In [5]:
aggregated = df.groupby('protein').agg(list)

In [6]:
aggregated

,aa,pos,x,y
protein,,,,
A0JNW5,"[S, S, T, S, T, T, T, T, S, T, S, S, S, T, S, ...","[414, 418, 420, 423, 427, 429, 438, 441, 443, ...",[TKNGWANELLHEFECNVEMLKQAVKDHNVGSPPKSPTHASPQHTQ...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
A0MZ66,"[S, S, T, S, S, S, S, S, S, S, S, T, S, S, S, ...","[3, 4, 14, 15, 82, 101, 153, 233, 249, 255, 25...",[XXXXXXXXXXXXXXXXXXXXXXXXXXXXMNSSDEEKQLQLITSLK...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
A1A5D9,"[S, S, S, S, S, S, S, S, S, S, S, S, S, S, S, ...","[3, 8, 11, 15, 19, 21, 36, 151, 154, 252, 267,...",[XXXXXXXXXXXXXXXXXXXXXXXXXXXXMSSPDGPSFPSGPLSGG...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
A1L4K1,"[S, T, S, S, S, T, S, S, S, S, T, S, S, S, T, ...","[5, 153, 158, 457, 460, 467, 470, 599, 601, 29...",[XXXXXXXXXXXXXXXXXXXXXXXXXXMEEESGEELGLDRSTPKDF...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, ..."
A1Z1Q3,"[S, S, S, T, S]","[258, 276, 334, 390, 401]",[DFKIYKKKMNEFFSVDDNNEEEEDVEMKEDSDENGPEEKQSVEEM...,"[1, 1, 1, 1, 1]"
...,...,...,...,...
Q9Y6P5,"[S, S]","[313, 314]",[LQECRDEEEASQEEMASRFEIEKRESMFVFSSDDEEVTPARAVSR...,"[1, 1]"
Q9Y6R0,"[S, S, S, T, S, T, T, T, S, T, S, S, S, S, S, ...","[215, 224, 228, 251, 263, 265, 268, 269, 270, ...",[SHAVGCAFAACLERKQRREKECGVTAAFDASRTSFAREGSFRLSG...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
Q9Y6R9,"[S, T, T, S, T, S, S, T, S, S, S, S, S, S, S, ...","[106, 170, 273, 274, 285, 334, 336, 338, 373, ...",[TQSSESVTLDLLTYTDLESLRNRKMGGRPGSLAPRSAQLNSKRYL...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
Q9Y6X8,"[T, S, S, T, T, S, S, S, S, S, S, T, S, S, S, ...","[37, 54, 55, 207, 439, 578, 624, 625, 628, 630...",[STTPCMVRTSQVVEQDVPEEVDRAKEKGIGTPQPDVAKDSWAAEL...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
Q9Y6X9,"[T, S, S, T, S, T, S, S, S, T, T, S, S, S, S, ...","[91, 513, 514, 599, 602, 603, 615, 627, 631, 6...",[GFMLCFLDDGAGMDPSDAASVIQFGKSAKRTPESTQIGQYGNGLK...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."

Create a Uniprot query list

In [7]:
",".join(aggregated.index.to_list())

'A0JNW5,A0MZ66,A1A5D9,A1L4K1,A1Z1Q3,A2VDJ0,A4D1E1,A4D1P6,A5PL33,A5PLL1,A6NC98,A6NCI4,A6NCL7,A6NDG6,A6NDU8,A6NE52,A6NGB9,A6NHR9,A6NIX2,A6NJL1,A6NKF1,A6NMB9,A6NMD0,A8K0R7,A8MVW0,B1AJZ9,C9JH25,D6RIA3,L0R6Q1,L0R819,O00139,O00178,O00186,O00244,O00257,O00329,O00461,O00468,O00476,O00512,O00629,O00748,O14494,O14653,O14737,O14770,O14791,O14933,O14944,O15013,O15060,O15205,O15381,O15397,O15400,O15417,O15488,O15540,O15550,O43155,O43156,O43172,O43173,O43181,O43184,O43187,O43283,O43295,O43310,O43399,O43402,O43424,O43561,O43586,O43704,O43734,O43747,O43776,O43795,O43805,O43813,O43824,O43915,O60242,O60245,O60285,O60343,O60356,O60359,O60488,O60502,O60583,O60610,O60667,O60828,O60888,O75052,O75069,O75112,O75200,O75323,O75335,O75340,O75420,O75438,O75452,O75503,O75506,O75554,O75608,O75618,O75674,O75807,O75821,O75864,O75907,O75912,O75914,O75952,O76031,O77932,O94760,O94763,O94766,O94776,O94788,O94804,O94818,O94822,O94823,O94826,O94868,O94885,O94886,O95057,O95073,O95149,O95180,O95208,O95219,O95243,O95271,O95294,O95342,O95361,O95428,O95478,O95528,O95602,O95670,O95677,O95749,O95758,O95835,O95865,O95873,O95886,O96009,O96011,P00813,P00918,P01031,P01213,P01860,P02671,P02679,P02686,P02730,P04003,P04040,P04049,P04070,P04090,P04217,P04275,P04433,P05093,P05114,P05156,P05412,P05783,P06241,P06396,P06401,P07108,P07306,P07307,P07339,P07357,P07919,P07947,P07954,P08247,P08294,P08473,P08670,P09104,P09110,P09132,P09211,P09651,P0C7P0,P0C7X2,P0CAP1,P0CI00,P0CJ79,P0DKB5,P0DMB2,P0DMV9,P10075,P10606,P10635,P10809,P10909,P11166,P11172,P11387,P11498,P12829,P12956,P13798,P13807,P13945,P14317,P14373,P14598,P14866,P14902,P15121,P15173,P15880,P16066,P16234,P16298,P16615,P17019,P17275,P17980,P18825,P18859,P19013,P19484,P19883,P20592,P20645,P20742,P20774,P20807,P20815,P20823,P20916,P20936,P21397,P21860,P21980,P22004,P22087,P22413,P22736,P23141,P23193,P23368,P23378,P23470,P23677,P23759,P24462,P24530,P24592,P24666,P25024,P25105,P25189,P25705,P25815,P25942,P26196,P26641,P26885,P27169,P27797,P28223,P29353,P29474,P29536,P29972,P30043,P30203,P30520,P30556,P30566,P30793,P31151,P31249,P31267,P31942,P32238,P32243,P33316,P33402,P33991,P34949,P35222,P35499,P35520,P35573,P35754,P35869,P35916,P35968,P36405,P36915,P36952,P36954,P36980,P37287,P37802,P38570,P40855,P41180,P41181,P41743,P42704,P42768,P43155,P43366,P43489,P45379,P45844,P46100,P46531,P46821,P47813,P47974,P47989,P48050,P48067,P48444,P48643,P48745,P49221,P49335,P49459,P49662,P49711,P49748,P49757,P49760,P49792,P49840,P49841,P49862,P49914,P50135,P50222,P50453,P50458,P50583,P51148,P51151,P51452,P51608,P51798,P51811,P51826,P51888,P51957,P52179,P52757,P53355,P53582,P53611,P54277,P54278,P54819,P55345,P55773,P55786,P57071,P57086,P57737,P57771,P57772,P60201,P60468,P61026,P61106,P61224,P61278,P61764,P61964,P62273,P62330,P62333,P62760,P62861,P62888,P62906,P62917,P62993,P63098,P63165,P78317,P78371,P78386,P78415,P78417,P78424,P81274,P81408,P82251,P82650,P82932,P98170,Q00059,Q00796,Q01082,Q01518,Q01860,Q02577,Q02763,Q02978,Q03154,Q03468,Q03519,Q04656,Q04721,Q04726,Q05193,Q05397,Q06413,Q06418,Q06455,Q06587,Q06730,Q07021,Q07092,Q07837,Q07866,Q07890,Q07955,Q08257,Q08334,Q08357,Q08379,Q08945,Q09019,Q0P6D6,Q12768,Q12791,Q12815,Q12816,Q12824,Q12882,Q12899,Q12904,Q12907,Q12965,Q12968,Q13049,Q13064,Q13084,Q13094,Q13111,Q13206,Q13261,Q13268,Q13277,Q13336,Q13363,Q13367,Q13418,Q13425,Q13472,Q13478,Q13542,Q13555,Q13586,Q13613,Q13617,Q13627,Q13634,Q13753,Q13772,Q13823,Q13895,Q14134,Q14137,Q14186,Q14242,Q14320,Q14353,Q14439,Q14500,Q14566,Q14576,Q14596,Q14654,Q14677,Q14687,Q14714,Q14722,Q14746,Q14765,Q14894,Q14995,Q149N8,Q14BN4,Q14C87,Q15006,Q15008,Q15011,Q15022,Q15043,Q15050,Q15124,Q15269,Q15274,Q15286,Q15329,Q15424,Q15493,Q15652,Q15758,Q15762,Q15788,Q15833,Q15907,Q16401,Q16531,Q16534,Q16537,Q16602,Q16650,Q16655,Q16762,Q16763,Q16820,Q16827,Q16853,Q16864,Q17R98,Q1AE95,Q1HG44,Q2I0M4,Q2M218,Q2M385,Q2M3C6,Q2NL68,Q2QGD7,Q2TB10,Q32M78,Q32MH5,Q3B726,Q3B7T1,Q3B820,Q3MHD2,Q3MIP1,Q3ZCQ8,Q3ZCT1,Q3ZCW2,Q495M3,Q49AG3,Q4G0X4,Q4U2R8,Q4V9L6,Q52LA3,Q53EU6,Q53H96,Q587J7,Q58A45,Q5CZA5,Q5GH72,Q5GH73,Q5HYK7,Q5HYM0,Q5I0X4,Q5JRC9,Q5JTV8,Q5JV73,Q5R3I4,Q5R3K3,Q5SW79,Q5SYB0,Q5SYC1,Q5T2R2,Q5T5J6,Q5T5P2,Q5T619,Q5T7N2,Q5T8R8,Q5TAP6,Q5TEA3,Q5TH69,Q5U4N7,Q5U5X0,Q5U5X8,Q5VIR6,Q5VTD9,Q5VUB5,Q5VV17,Q5VWK0,Q5VWP2,Q5VWP3,Q5VYS8,Q5VZP5,Q5XKL5,Q63HQ0,Q684P5,Q68BL7,Q68CZ2,Q68D86,Q68DK2,Q68DV7,Q69YN4,Q6AI08,Q6AI14,Q6DKI7,Q6DN12,Q6IA17,Q6IMN6,Q6MZT1,Q6NUN9,Q6NVY1,Q6NXR4,Q6NYC1,Q6NZ36,Q6P1L5,Q6P1Q9,Q6P3R8,Q6P5Q4,Q6P9A1,Q6P9B6,Q6P9B9,Q6P9F7,Q6P9H4,Q6PEW0,Q6PGP7,Q6PID6,Q6PJI9,Q6PJW8,Q6PKG0,Q6SPF0,Q6T311,Q6TGC4,Q6UVJ0,Q6UWI4,Q6UWV2,Q6UXK5,Q6UXU4,Q6UY01,Q6VY07,Q6Y2X3,Q6ZMD2,Q6ZN55,Q6ZNA4,Q6ZQN7,Q6ZRI6,Q6ZRP7,Q6ZTU2,Q6ZU80,Q6ZVL6,Q75N03,Q76N89,Q7KZ85,Q7L1Q6,Q7L273,Q7L2J0,Q7L591,Q7L592,Q7L5A8,Q7L5D6,Q7L8C5,Q7LDG7,Q7RTS1,Q7RTT9,Q7Z2Y5,Q7Z392,Q7Z3E2,Q7Z3U7,Q7Z407,Q7Z412,Q7Z494,Q7Z4T8,Q7Z5N4,Q7Z6E9,Q7Z6I6,Q7Z6J2,Q7Z6J9,Q7Z7G0,Q7Z7G8,Q7Z7K6,Q7Z7L7,Q7Z7M8,Q86SF2,Q86SJ6,Q86SQ0,Q86SS6,Q86U28,Q86VH4,Q86VP1,Q86WK6,Q86X29,Q86XE3,Q86XK2,Q86YD3,Q86YL5,Q86YN6,Q86YS3,Q86YV9,Q86Z20,Q8IUD6,Q8IUH4,Q8IUY3,Q8IV31,Q8IV56,Q8IVA1,Q8IVF2,Q8IVP5,Q8IVT2,Q8IW93,Q8IWA5,Q8IWB6,Q8IWE5,Q8IWR0,Q8IWR1,Q8IWT3,Q8IWU5,Q8IXI2,Q8IXQ3,Q8IXT1,Q8IXV7,Q8IXX5,Q8IXZ2,Q8IY21,Q8IY37,Q8IY63,Q8IYA6,Q8IYB1,Q8IYE1,Q8IYL9,Q8IYT2,Q8IZ40,Q8IZC4,Q8IZD2,Q8IZD9,Q8IZL2,Q8N0W4,Q8N0X7,Q8N108,Q8N141,Q8N187,Q8N196,Q8N2K0,Q8N336,Q8N392,Q8N3E9,Q8N3L3,Q8N3X6,Q8N531,Q8N554,Q8N5H3,Q8N5M4,Q8N612,Q8N684,Q8N6F8,Q8N6K0,Q8N6L1,Q8N6N3,Q8N720,Q8N726,Q8N7U6,Q8N8F7,Q8N8K9,Q8N8S7,Q8N8U9,Q8N960,Q8N9B8,Q8N9M1,Q8N9U0,Q8N9V3,Q8NA03,Q8NB15,Q8NBJ4,Q8NBN3,Q8NBT2,Q8NCF0,Q8NDA2,Q8NDH3,Q8NDX5,Q8NE62,Q8NEA6,Q8NEL9,Q8NEP7,Q8NET8,Q8NEU8,Q8NFC6,Q8NFH8,Q8NFJ8,Q8NFP7,Q8NFT8,Q8NG31,Q8NHV4,Q8TA94,Q8TAF3,Q8TB03,Q8TB36,Q8TB45,Q8TB52,Q8TBY9,Q8TBZ2,Q8TC07,Q8TCT7,Q8TDN6,Q8TDX7,Q8TE82,Q8TE85,Q8TEB9,Q8TES7,Q8TF17,Q8TF39,Q8TF72,Q8WTR7,Q8WU43,Q8WUA7,Q8WUB2,Q8WUD1,Q8WUD4,Q8WUJ0,Q8WUP2,Q8WV99,Q8WW12,Q8WWG9,Q8WWK9,Q8WWT9,Q8WXD2,Q8WXH2,Q8WXS3,Q8WY36,Q8WY41,Q8WY54,Q8WYA6,Q8WYB5,Q8WYJ6,Q8WYQ3,Q8WYQ4,Q92466,Q92522,Q92542,Q92552,Q92561,Q92574,Q92665,Q92747,Q92754,Q92826,Q92843,Q92925,Q92953,Q92979,Q93015,Q93100,Q969G3,Q969T3,Q969U6,Q969W3,Q96A19,Q96A33,Q96A35,Q96A49,Q96AC1,Q96AC6,Q96AE7,Q96AP0,Q96AY2,Q96B21,Q96B86,Q96B96,Q96BI3,Q96BN2,Q96BR1,Q96C03,Q96CC6,Q96CM3,Q96D42,Q96DH6,Q96DN6,Q96DX4,Q96EK5,Q96EK9,Q96EL2,Q96EY8,Q96F86,Q96FQ7,Q96FS4,Q96FT7,Q96G23,Q96G61,Q96GD3,Q96GD4,Q96GX2,Q96GZ6,Q96HC4,Q96HD1,Q96HE8,Q96HJ9,Q96I36,Q96IX5,Q96IZ0,Q96J77,Q96J88,Q96JB5,Q96JG9,Q96JJ7,Q96JM3,Q96JM7,Q96KG7,Q96KN1,Q96KN3,Q96KN9,Q96KQ7,Q96KV7,Q96L93,Q96LW9,Q96M11,Q96M29,Q96ME7,Q96MU7,Q96MY1,Q96MZ0,Q96N96,Q96NE9,Q96NX9,Q96PD2,Q96PP8,Q96PR1,Q96PV0,Q96PZ0,Q96RG2,Q96RK1,Q96S21,Q96S38,Q96S66,Q96T49,Q96T58,Q99453,Q99576,Q99674,Q99676,Q99687,Q99719,Q99733,Q99735,Q9BPU6,Q9BQ50,Q9BQ95,Q9BQI5,Q9BQI7,Q9BRA0,Q9BRD0,Q9BRF8,Q9BRQ0,Q9BRQ5,Q9BS16,Q9BSE5,Q9BSK4,Q9BSW7,Q9BT23,Q9BT88,Q9BU76,Q9BUB4,Q9BUH8,Q9BUP0,Q9BV35,Q9BV36,Q9BV73,Q9BVA0,Q9BVJ6,Q9BVS5,Q9BVT8,Q9BX10,Q9BX68,Q9BXB4,Q9BXF9,Q9BXQ6,Q9BXS5,Q9BXY0,Q9BY42,Q9BYE2,Q9BYE7,Q9BYV2,Q9BYV7,Q9BZC7,Q9BZF3,Q9BZR8,Q9C004,Q9C010,Q9C037,Q9C091,Q9C0K7,Q9GZR1,Q9GZY8,Q9GZZ0,Q9H098,Q9H0A8,Q9H0D6,Q9H0F6,Q9H0I2,Q9H0K6,Q9H0T7,Q9H0U9,Q9H0X4,Q9H169,Q9H175,Q9H1H9,Q9H1R2,Q9H1Y3,Q9H2E6,Q9H2H0,Q9H2M9,Q9H2U2,Q9H2X6,Q9H336,Q9H3G5,Q9H3R5,Q9H3Y6,Q9H467,Q9H4I8,Q9H4K1,Q9H582,Q9H5Y7,Q9H6D8,Q9H6E5,Q9H6R3,Q9H6U8,Q9H7M9,Q9H7Z3,Q9H814,Q9H898,Q9H8G2,Q9H8H3,Q9H8J5,Q9H8K7,Q9H8T0,Q9H910,Q9H974,Q9H9P5,Q9H9T3,Q9H9Y4,Q9HA47,Q9HA92,Q9HAB8,Q9HAD4,Q9HAK2,Q9HAN9,Q9HAU5,Q9HAZ1,Q9HB58,Q9HBA0,Q9HC97,Q9HC98,Q9HCD5,Q9HCD6,Q9HCJ3,Q9HCY8,Q9NNW7,Q9NP58,Q9NP79,Q9NP84,Q9NP87,Q9NPF8,Q9NPG8,Q9NPI7,Q9NPJ6,Q9NPR9,Q9NPY3,Q9NQ32,Q9NQ48,Q9NQ75,Q9NQ89,Q9NQC7,Q9NQG5,Q9NQG6,Q9NQX0,Q9NQX5,Q9NQZ6,Q9NR00,Q9NR30,Q9NR81,Q9NR97,Q9NRA0,Q9NRC1,Q9NRG0,Q9NRN7,Q9NRP4,Q9NRW1,Q9NRW4,Q9NRX1,Q9NRX2,Q9NS37,Q9NS40,Q9NSC7,Q9NT22,Q9NT68,Q9NTJ5,Q9NTK1,Q9NTX7,Q9NUD5,Q9NUL5,Q9NUQ3,Q9NUU7,Q9NV29,Q9NV72,Q9NV79,Q9NV92,Q9NVA1,Q9NVR7,Q9NWD8,Q9NWT8,Q9NX57,Q9NX65,Q9NXD2,Q9NY57,Q9NY61,Q9NYA4,Q9NYB5,Q9NYB9,Q9NYD6,Q9NYP3,Q9NYT6,Q9NZ94,Q9NZH6,Q9NZL4,Q9NZQ8,Q9NZT1,Q9P016,Q9P0K7,Q9P0K9,Q9P0X4,Q9P127,Q9P1A6,Q9P1Z0,Q9P1Z3,Q9P1Z9,Q9P203,Q9P209,Q9P241,Q9P296,Q9P2E3,Q9P2F8,Q9P2H5,Q9P2K1,Q9P2P6,Q9P2R3,Q9UBE8,Q9UBG3,Q9UBJ2,Q9UBT2,Q9UBY0,Q9UBZ4,Q9UBZ9,Q9UD57,Q9UDR5,Q9UDT6,Q9UEY8,Q9UF83,Q9UGI6,Q9UGN5,Q9UHJ3,Q9UHL4,Q9UHN6,Q9UHP9,Q9UHQ1,Q9UI14,Q9UIG0,Q9UIG8,Q9UIJ5,Q9UIK5,Q9UIL8,Q9UJ04,Q9UJ68,Q9UJ72,Q9UJF2,Q9UK13,Q9UK22,Q9UK45,Q9UKA8,Q9UKL3,Q9UKN8,Q9UKQ2,Q9UKW4,Q9UKY4,Q9UL45,Q9UL63,Q9ULD5,Q9ULI0,Q9ULJ7,Q9ULL5,Q9ULM0,Q9ULZ2,Q9UM21,Q9UMR2,Q9UMR3,Q9UMZ2,Q9UNF1,Q9UNP9,Q9UNW9,Q9UNY4,Q9UNZ2,Q9UP79,Q9UPC5,Q9UPN3,Q9UPQ3,Q9UPR0,Q9UPR3,Q9UPT9,Q9UPZ3,Q9UQ49,Q9Y248,Q9Y2B5,Q9Y2G4,Q9Y2I9,Q9Y2J8,Q9Y2L9,Q9Y2R0,Q9Y2R2,Q9Y2R5,Q9Y2V7,Q9Y2W6,Q9Y2W7,Q9Y2X0,Q9Y315,Q9Y316,Q9Y320,Q9Y365,Q9Y366,Q9Y3B1,Q9Y3B4,Q9Y3D7,Q9Y3Q8,Q9Y3S1,Q9Y4F3,Q9Y4G2,Q9Y4G6,Q9Y4H4,Q9Y4X5,Q9Y592,Q9Y5B9,Q9Y5E6,Q9Y5J3,Q9Y5K3,Q9Y5Q6,Q9Y614,Q9Y625,Q9Y692,Q9Y6A5,Q9Y6P5,Q9Y6R0,Q9Y6R9,Q9Y6X8,Q9Y6X9'

Create a prot info

In [8]:
mapping = pd.read_csv('../data/deepmvp/idmapping_2026_04_27.tsv', sep='\t')

FileNotFoundError: [Errno 2] No such file or directory: '../data/deepmvp/idmapping_2026_04_27.tsv'

In [9]:
joined = mapping.set_index('From').join(aggregated)

Check if all match

In [10]:
(joined.Entry != joined.index).sum()

np.int64(0)

In [ ]:
temp_info = joined[['Entry','pos', 'y', 'Sequence']]

In [ ]:
temp_info = temp_info.rename(columns={'Entry' : 'id', 'pos' : 'sites', 'y' : 'labels', 'Sequence' : 'sequence'})

In [19]:
import numpy as np

def filter_fn(row):
    mask = [label == 1 for label in row['labels']]
    return np.asarray(row['sites'])[mask]

In [ ]:
temp_info['sites'] = temp_info.apply(filter_fn, axis=1)

In [ ]:
temp_info['sites']

From
A0JNW5    [414, 418, 420, 423, 427, 429, 438, 441, 443, ...
A0MZ66    [3, 4, 14, 15, 82, 101, 153, 233, 249, 255, 25...
A1A5D9    [3, 8, 11, 15, 19, 21, 36, 151, 154, 252, 267,...
A1L4K1          [5, 153, 158, 457, 460, 467, 470, 599, 601]
A1Z1Q3                            [258, 276, 334, 390, 401]
                                ...
Q9Y6A5    [2, 12, 25, 39, 56, 59, 71, 73, 87, 133, 138, ...
Q9Y6P5                                           [313, 314]
Q9Y6R0    [215, 224, 228, 251, 263, 265, 268, 269, 270, ...
Q9Y6R9    [106, 170, 273, 274, 285, 334, 336, 338, 373, ...
Q9Y6X8    [37, 54, 55, 207, 439, 578, 624, 625, 628, 630...
Name: sites, Length: 1260, dtype: object

In [ ]:
temp_info['original_label'] = 'test'

In [ ]:
test_path = '../data/deepmvp/phos_st_training.tsv'
df = pd.read_csv(test_path, sep='\t')
grouped = df.groupby('protein').agg(list)
",".join(grouped.index.to_list())

'A0A024RBG1,A0A075B6I4,A0A075B767,A0A096LP49,A0A0A0MS14,A0A0B4J266,A0A0B4J279,A0A0B4J2A2,A0A0B4J2F0,A0A0B4J2F2,A0A0J9YX94,A0A0J9YY54,A0A0U1RRE5,A0A0U1RRI6,A0A0U1RRK4,A0A1B0GTK4,A0A1B0GTU1,A0A1B0GUA9,A0A1B0GUC4,A0A1B0GUJ8,A0A1B0GV03,A0A1B0GVQ0,A0A1B0GVZ6,A0A1B0GWB2,A0A1B0GWG4,A0A2R8YCJ5,A0A5B6,A0AUZ9,A0AV02,A0AV96,A0AVI2,A0AVK6,A0AVT1,A0FGR8,A0FGR9,A0JLT2,A0PJW6,A0PJW8,A0PJX4,A0PJY2,A0PK00,A0PK05,A1A4G5,A1A4S6,A1A5C7,A1IGU5,A1KXE4,A1L020,A1L0T0,A1L162,A1L168,A1L170,A1L188,A1L390,A1L429,A1L4H1,A1X283,A1XBS5,A1YPR0,A2A288,A2A2V5,A2A2Y4,A2A3K4,A2A3N6,A2AJT9,A2IDD5,A2RRD8,A2RRP1,A2RTX5,A2RU30,A2RU54,A2RU67,A2RUB1,A2RUB6,A2RUR9,A2RUS2,A2VCK2,A2VDF0,A3KMH1,A3KN83,A4D126,A4D161,A4D1S0,A4D1S5,A4D1U4,A4D2B0,A4D2H0,A4D2P6,A4FU01,A4FU28,A4FU49,A4FU69,A4QPH2,A4UGR9,A5A3E0,A5D6W6,A5D8V6,A5D8V7,A5PKW4,A5PLN7,A5PLN9,A5YKK6,A5YM69,A5YM72,A6BM72,A6H8M9,A6H8Y1,A6NC57,A6NC78,A6NCC3,A6NCI8,A6NCQ9,A6NCS4,A6NCS6,A6ND36,A6ND91,A6NDB9,A6NDE4,A6NE82,A6NEC2,A6NED2,A6NEE1,A6NEL2,A6NEQ0,A6NEQ2,A6NES4,A6NF01,A6NFI3,A6NFR6,A6NFX1,A6NFY7,A6NGB7,A6NGC4,A6NGE4,A6NGG8,A6NGN9,A6NGR9,A6NGS2,A6NHG4,A6NHJ4,A6NHN6,A6NHQ4,A6NHT5,A6NI28,A6NI72,A6NI79,A6NIE6,A6NIH7,A6NIK2,A6NIY4,A6NJ46,A6NJ64,A6NJ78,A6NJG2,A6NJI1,A6NJT0,A6NJZ7,A6NK44,A6NK89,A6NKB5,A6NKD9,A6NKF7,A6NKG5,A6NKL6,A6NKN8,A6NKT7,A6NKU9,A6NL88,A6NLC5,A6NLJ0,A6NM28,A6NMD2,A6NMK8,A6NMT0,A6NMX2,A6NMY6,A6NMZ7,A6NN90,A6NNA2,A6NNA5,A6NNC1,A6NNE9,A6NNM3,A6NNY8,A6NNZ2,A6PVY3,A6QL63,A6QL64,A7E2F4,A7E2U8,A7E2V4,A7E2Y1,A7KAX9,A7MBM2,A7MCY6,A7MD48,A7XYQ1,A8CG34,A8K0Z3,A8K2U0,A8K5M9,A8K855,A8K8P3,A8K979,A8MPP1,A8MPS7,A8MQ03,A8MQ14,A8MQ27,A8MRT5,A8MT19,A8MT65,A8MT70,A8MTA8,A8MTJ3,A8MTJ6,A8MTL3,A8MTQ0,A8MTZ7,A8MU46,A8MU93,A8MUH7,A8MUU9,A8MV81,A8MVS1,A8MVS5,A8MVU1,A8MVX0,A8MW92,A8MWX3,A8MWY0,A8MX76,A8MXT2,A8MXV4,A8MYA2,A8MYP8,A8MYZ6,A8MZ97,A8MZF0,A8TX70,A9UHW6,A9YTQ3,B0FP48,B0I1T2,B0YJ81,B1AK53,B1ANS9,B2RBV5,B2RPK0,B2RTY4,B2RU33,B2RUZ4,B2RXF0,B2RXF5,B2RXH2,B3EWG6,B3KU38,B4DH59,B4DJY2,B4DS77,B7U540,B7Z1M9,B7Z6K7,B7ZAP0,B7ZBB8,B7ZC32,B9A064,C4AMC7,C9J069,C9J202,C9J798,C9J7I0,C9JG80,C9JI98,C9JLR9,C9JLW8,C9JQI7,C9JQL5,C9JRZ8,C9JTQ0,C9JVW0,D6RF30,D6RGH6,E5RHQ5,E5RIL1,E7ERA6,E7ETH6,E7EW31,E9PAV3,E9PB15,E9PGG2,E9PRG8,F5GYI3,F5H284,F5H4A9,F8WCM5,G2XKQ0,G3V0H7,G9CGD6,H0YL14,H3BPF8,H3BQB6,H3BQL2,H3BR10,H3BRN8,H3BSY2,H7BZ55,I3L273,I3L3R5,I6L899,K7EJ46,M0QZC1,M0R2J8,M5A8F1,O00116,O00124,O00141,O00148,O00151,O00154,O00155,O00159,O00160,O00161,O00165,O00167,O00168,O00170,O00180,O00182,O00189,O00192,O00193,O00194,O00203,O00204,O00212,O00213,O00214,O00217,O00220,O00221,O00222,O00231,O00232,O00233,O00238,O00255,O00264,O00267,O00268,O00273,O00287,O00291,O00294,O00299,O00300,O00303,O00305,O00308,O00311,O00321,O00327,O00330,O00337,O00338,O00358,O00370,O00391,O00400,O00401,O00408,O00409,O00410,O00411,O00418,O00421,O00422,O00423,O00425,O00429,O00442,O00443,O00444,O00453,O00458,O00459,O00462,O00463,O00469,O00470,O00471,O00472,O00478,O00479,O00481,O00483,O00487,O00488,O00499,O00501,O00505,O00506,O00507,O00515,O00519,O00522,O00533,O00534,O00541,O00548,O00555,O00559,O00560,O00562,O00566,O00567,O00570,O00571,O00574,O00585,O00590,O00591,O00592,O00622,O00623,O00625,O00635,O00712,O00716,O00743,O00744,O00746,O00750,O00754,O00757,O00762,O00763,O00764,O00767,O14490,O14492,O14493,O14495,O14497,O14503,O14508,O14511,O14513,O14514,O14519,O14520,O14522,O14523,O14524,O14525,O14526,O14529,O14530,O14531,O14543,O14544,O14545,O14548,O14558,O14559,O14561,O14562,O14576,O14578,O14579,O14594,O14595,O14598,O14602,O14604,O14607,O14613,O14617,O14618,O14626,O14628,O14638,O14639,O14640,O14641,O14645,O14646,O14647,O14649,O14654,O14662,O14668,O14672,O14681,O14682,O14683,O14686,O14713,O14715,O14727,O14730,O14732,O14733,O14734,O14744,O14745,O14753,O14756,O14757,O14771,O14772,O14773,O14775,O14776,O14777,O14782,O14786,O14787,O14795,O14796,O14798,O14802,O14807,O14810,O14813,O14818,O14827,O14828,O14829,O14830,O14832,O14836,O14841,O14843,O14862,O14863,O14867,O14874,O14879,O14880,O14893,O14896,O14901,O14907,O14908,O14910,O14917,O14920,O14924,O14929,O14936,O14939,O14948,O14949,O14958,O14964,O14965,O14966,O14967,O14974,O14975,O14976,O14978,O14979,O14980,O14981,O14983,O14986,O14994,O15014,O15015,O15016,O15018,O15020,O15021,O15027,O15031,O15033,O15034,O15037,O15040,O15042,O15047,O15049,O15050,O15054,O15055,O15056,O15061,O15062,O15063,O15066,O15067,O15068,O15069,O15075,O15078,O15079,O15083,O15084,O15085,O15090,O15091,O15111,O15116,O15117,O15118,O15119,O15120,O15121,O15126,O15127,O15131,O15143,O15144,O15145,O15146,O15151,O15155,O15156,O15160,O15162,O15164,O15165,O15169,O15172,O15173,O15178,O15182,O15194,O15195,O15197,O15198,O15204,O15209,O15211,O15212,O15213,O15218,O15226,O15228,O15229,O15231,O15232,O15234,O15239,O15240,O15243,O15244,O15245,O15247,O15254,O15258,O15260,O15264,O15265,O15269,O15270,O15273,O15287,O15294,O15296,O15297,O15304,O15305,O15318,O15321,O15327,O15344,O15347,O15350,O15353,O15354,O15355,O15357,O15360,O15370,O15371,O15372,O15374,O15375,O15379,O15389,O15391,O15392,O15393,O15394,O15399,O15403,O15405,O15409,O15427,O15431,O15432,O15438,O15439,O15440,O15446,O15455,O15460,O15479,O15481,O15484,O15492,O15498,O15503,O15504,O15511,O15514,O15516,O15523,O15525,O15530,O15533,O15534,O15541,O15551,O15552,O15553,O15554,O43143,O43147,O43148,O43149,O43150,O43151,O43157,O43159,O43164,O43166,O43167,O43169,O43175,O43182,O43189,O43194,O43236,O43237,O43240,O43242,O43246,O43247,O43248,O43251,O43252,O43255,O43264,O43272,O43281,O43290,O43291,O43292,O43293,O43294,O43296,O43298,O43299,O43300,O43301,O43303,O43304,O43306,O43307,O43309,O43312,O43313,O43314,O43315,O43318,O43324,O43325,O43345,O43347,O43353,O43361,O43365,O43374,O43379,O43390,O43395,O43396,O43414,O43422,O43423,O43426,O43432,O43435,O43439,O43447,O43448,O43463,O43464,O43474,O43482,O43488,O43490,O43491,O43493,O43497,O43502,O43504,O43505,O43513,O43516,O43520,O43521,O43524,O43525,O43526,O43541,O43543,O43548,O43555,O43556,O43559,O43566,O43567,O43570,O43572,O43581,O43583,O43592,O43593,O43597,O43598,O43602,O43603,O43609,O43610,O43613,O43615,O43623,O43633,O43638,O43639,O43660,O43663,O43665,O43670,O43674,O43676,O43678,O43679,O43680,O43681,O43683,O43684,O43687,O43688,O43699,O43707,O43708,O43709,O43711,O43716,O43719,O43736,O43741,O43745,O43752,O43759,O43760,O43761,O43765,O43768,O43772,O43781,O43790,O43791,O43808,O43815,O43818,O43819,O43822,O43823,O43829,O43837,O43847,O43852,O43861,O43865,O43868,O43889,O43895,O43896,O43900,O43903,O43909,O43913,O43914,O43916,O43920,O43924,O43929,O43930,O43933,O43934,O60216,O60218,O60220,O60229,O60231,O60232,O60234,O60237,O60238,O60239,O60240,O60241,O60244,O60248,O60256,O60260,O60262,O60264,O60266,O60268,O60269,O60271,O60279,O60281,O60282,O60284,O60287,O60290,O60291,O60292,O60293,O60294,O60296,O60299,O60303,O60304,O60306,O60307,O60308,O60312,O60313,O60315,O60318,O60320,O60331,O60333,O60336,O60337,O60341,O60346,O60347,O60353,O60361,O60381,O60391,O60393,O60427,O60437,O60443,O60447,O60449,O60462,O60469,O60476,O60478,O60481,O60486,O60487,O60493,O60496,O60499,O60500,O60503,O60504,O60506,O60507,O60508,O60516,O60518,O60522,O60524,O60547,O60548,O60551,O60563,O60565,O60566,O60568,O60573,O60613,O60637,O60641,O60645,O60656,O60658,O60662,O60663,O60664,O60669,O60671,O60673,O60674,O60675,O60678,O60682,O60683,O60684,O60701,O60704,O60706,O60711,O60716,O60729,O60732,O60733,O60739,O60741,O60749,O60759,O60762,O60763,O60765,O60779,O60784,O60812,O60814,O60825,O60826,O60829,O60831,O60832,O60841,O60858,O60861,O60869,O60870,O60879,O60883,O60884,O60885,O60890,O60902,O60907,O60921,O60925,O60927,O60928,O60930,O60934,O60936,O60939,O60941,O60942,O75022,O75023,O75027,O75030,O75037,O75038,O75044,O75051,O75054,O75056,O75061,O75064,O75071,O75074,O75077,O75081,O75083,O75084,O75094,O75095,O75096,O75110,O75113,O75116,O75121,O75122,O75123,O75127,O75128,O75129,O75131,O75132,O75140,O75143,O75145,O75146,O75147,O75150,O75151,O75152,O75153,O75154,O75155,O75157,O75159,O75161,O75164,O75165,O75167,O75170,O75175,O75179,O75182,O75190,O75191,O75192,O75197,O75204,O75208,O75223,O75251,O75264,O75290,O75298,O75309,O75312,O75319,O75324,O75330,O75334,O75343,O75347,O75348,O75351,O75355,O75356,O75362,O75363,O75364,O75366,O75367,O75368,O75369,O75376,O75379,O75381,O75382,O75385,O75386,O75387,O75390,O75391,O75396,O75398,O75400,O75410,O75417,O75419,O75425,O75427,O75431,O75436,O75439,O75444,O75445,O75446,O75448,O75449,O75459,O75460,O75461,O75462,O75467,O75473,O75475,O75477,O75478,O75486,O75487,O75489,O75494,O75496,O75508,O75509,O75521,O75525,O75526,O75528,O75529,O75530,O75531,O75533,O75534,O75541,O75553,O75558,O75563,O75564,O75569,O75575,O75581,O75582,O75586,O75592,O75593,O75596,O75602,O75604,O75607,O75616,O75626,O75628,O75631,O75638,O75643,O75663,O75665,O75676,O75683,O75688,O75689,O75691,O75694,O75695,O75712,O75716,O75717,O75718,O75746,O75747,O75751,O75762,O75764,O75781,O75787,O75791,O75792,O75794,O75800,O75808,O75815,O75817,O75820,O75822,O75828,O75829,O75832,O75843,O75844,O75845,O75871,O75874,O75881,O75884,O75886,O75888,O75891,O75896,O75897,O75899,O75909,O75911,O75915,O75920,O75923,O75925,O75928,O75934,O75935,O75936,O75937,O75940,O75943,O75947,O75953,O75955,O75956,O75962,O75964,O75969,O75970,O75971,O75976,O75995,O76003,O76013,O76015,O76021,O76024,O76027,O76038,O76039,O76041,O76050,O76054,O76061,O76064,O76070,O76071,O76074,O76076,O76080,O76081,O76082,O76083,O76087,O76094,O94759,O94761,O94762,O94768,O94769,O94772,O94778,O94782,O94805,O94806,O94808,O94811,O94812,O94819,O94827,O94829,O94830,O94832,O94842,O94844,O94850,O94851,O94854,O94855,O94856,O94864,O94874,O94875,O94876,O94880,O94887,O94888,O94889,O94892,O94898,O94900,O94901,O94903,O94905,O94906,O94907,O94910,O94911,O94913,O94915,O94916,O94919,O94921,O94923,O94925,O94927,O94929,O94933,O94941,O94953,O94955,O94956,O94964,O94966,O94967,O94972,O94973,O94979,O94983,O94985,O94986,O94988,O94989,O94991,O94992,O94993,O95049,O95050,O95067,O95069,O95070,O95071,O95072,O95076,O95081,O95096,O95104,O95125,O95136,O95139,O95140,O95150,O95153,O95154,O95155,O95159,O95163,O95164,O95167,O95168,O95171,O95182,O95183,O95185,O95196,O95197,O95199,O95201,O95202,O95206,O95210,O95218,O95229,O95231,O95232,O95235,O95236,O95238,O95239,O95248,O95249,O95251,O95255,O95259,O95260,O95263,O95267,O95274,O95279,O95292,O95295,O95297,O95298,O95299,O95319,O95336,O95340,O95343,O95347,O95352,O95359,O95365,O95372,O95373,O95376,O95379,O95382,O95391,O95394,O95396,O95398,O95400,O95402,O95405,O95409,O95415,O95425,O95429,O95433,O95436,O95447,O95452,O95453,O95456,O95461,O95466,O95467,O95470,O95471,O95475,O95476,O95477,O95479,O95484,O95486,O95487,O95490,O95500,O95502,O95503,O95544,O95551,O95562,O95568,O95571,O95573,O95600,O95613,O95622,O95625,O95626,O95628,O95630,O95633,O95639,O95644,O95665,O95671,O95672,O95674,O95678,O95684,O95685,O95696,O95704,O95707,O95714,O95716,O95718,O95721,O95741,O95747,O95751,O95754,O95755,O95757,O95759,O95760,O95772,O95777,O95780,O95782,O95785,O95786,O95789,O95793,O95801,O95807,O95810,O95816,O95817,O95819,O95822,O95825,O95831,O95832,O95833,O95837,O95848,O95857,O95859,O95861,O95863,O95864,O95866,O95870,O95872,O95900,O95905,O95907,O95922,O95926,O95931,O95935,O95936,O95948,O95954,O95976,O95977,O95980,O95983,O95985,O95989,O95990,O95994,O95995,O95996,O95997,O95999,O96000,O96001,O96005,O96006,O96007,O96008,O96013,O96017,O96018,O96019,O96020,O96028,P00167,P00325,P00326,P00338,P00352,P00367,P00374,P00387,P00390,P00403,P00439,P00441,P00450,P00451,P00480,P00488,P00491,P00492,P00505,P00519,P00533,P00558,P00568,P00734,P00736,P00738,P00740,P00742,P00746,P00747,P00748,P00751,P00915,P00966,P00973,P00995,P01008,P01009,P01011,P01023,P01024,P01033,P01034,P01040,P01042,P01100,P01106,P01111,P01112,P01116,P01127,P01130,P01189,P01210,P01258,P01266,P01275,P01303,P01344,P01562,P01583,P01584,P01591,P01602,P01730,P01732,P01833,P01834,P01857,P01859,P01861,P01871,P01876,P01889,P01891,P01892,P01893,P01903,P01911,P02008,P02100,P02144,P02452,P02461,P02489,P02511,P02533,P02538,P02545,P02549,P02585,P02647,P02649,P02652,P02655,P02656,P02675,P02689,P02724,P02743,P02748,P02749,P02751,P02753,P02760,P02763,P02765,P02766,P02768,P02771,P02774,P02775,P02786,P02787,P02788,P02790,P02792,P02794,P02795,P02808,P03372,P03928,P03956,P03989,P04004,P04035,P04053,P04075,P04080,P04083,P04085,P04114,P04150,P04155,P04156,P04179,P04181,P04183,P04196,P04198,P04216,P04222,P04229,P04233,P04234,P04259,P04264,P04279,P04350,P04406,P04424,P04439,P04626,P04632,P04637,P04731,P04732,P04733,P04792,P04798,P04818,P04839,P04843,P04844,P04899,P04908,P04920,P04921,P05023,P05026,P05060,P05062,P05067,P05089,P05090,P05091,P05106,P05107,P05109,P05120,P05121,P05129,P05141,P05160,P05161,P05162,P05164,P05165,P05166,P05177,P05181,P05186,P05187,P05198,P05204,P05230,P05231,P05305,P05362,P05386,P05387,P05388,P05408,P05413,P05423,P05452,P05455,P05496,P05534,P05546,P05549,P05556,P05771,P05787,P05814,P05937,P05976,P05997,P06127,P06132,P06213,P06239,P06307,P06400,P06454,P06493,P06576,P06702,P06703,P06727,P06729,P06730,P06731,P06732,P06733,P06734,P06737,P06744,P06746,P06748,P06753,P06756,P06881,P07099,P07101,P07148,P07195,P07196,P07197,P07199,P07203,P07204,P07205,P07225,P07237,P07305,P07311,P07315,P07327,P07332,P07333,P07358,P07359,P07360,P07384,P07437,P07451,P07476,P07492,P07550,P07585,P07602,P07737,P07738,P07741,P07766,P07814,P07858,P07864,P07900,P07902,P07910,P07911,P07942,P07948,P07949,P07951,P07988,P07992,P07996,P07998,P08034,P08047,P08048,P08069,P08100,P08123,P08133,P08134,P08138,P08151,P08172,P08173,P08174,P08183,P08185,P08195,P08235,P08237,P08238,P08240,P08243,P08246,P08253,P08263,P08311,P08319,P08397,P08476,P08493,P08514,P08559,P08567,P08572,P08574,P08575,P08579,P08581,P08582,P08588,P08590,P08603,P08621,P08631,P08648,P08651,P08684,P08697,P08708,P08709,P08727,P08729,P08754,P08758,P08779,P08833,P08865,P08887,P08908,P08910,P08912,P08913,P08922,P08962,P08F94,P09001,P09012,P09016,P09017,P09038,P09067,P09086,P09210,P09234,P09238,P09327,P09382,P09417,P09429,P09467,P09471,P09488,P09493,P09496,P09497,P09525,P09543,P09564,P09565,P09601,P09603,P09619,P09622,P09630,P09661,P09669,P09693,P09758,P09769,P09871,P09874,P09884,P09912,P09913,P09914,P09923,P09936,P09958,P09960,P09972,P0C024,P0C091,P0C0L4,P0C0L5,P0C0S5,P0C0S8,P0C1Z6,P0C264,P0C2L3,P0C5K6,P0C623,P0C671,P0C6C1,P0C7M4,P0C7M8,P0C7P1,P0C7P4,P0C7T5,P0C7T7,P0C7T8,P0C7U0,P0C7U9,P0C7V6,P0C7V9,P0C7W0,P0C842,P0C851,P0C860,P0C869,P0C870,P0C881,P0CAP2,P0CF74,P0CG04,P0CG08,P0CG12,P0CG20,P0CG23,P0CG24,P0CG29,P0CG30,P0CG31,P0CG35,P0CG38,P0CG39,P0CG40,P0CG41,P0CG47,P0CG48,P0CJ78,P0CJ92,P0CK96,P0CK97,P0CL80,P0CL81,P0CL82,P0CL83,P0CW01,P0DI81,P0DI82,P0DI83,P0DJ93,P0DJD0,P0DJD1,P0DJD3,P0DJD4,P0DJI8,P0DJI9,P0DJJ0,P0DKX0,P0DM35,P0DME0,P0DMM9,P0DMN0,P0DMP2,P0DMS8,P0DMU7,P0DMU8,P0DMU9,P0DMV0,P0DMV1,P0DMV2,P0DMV8,P0DN24,P0DN26,P0DN37,P0DN79,P0DN80,P0DOX5,P0DOX7,P0DOX8,P0DOY2,P0DOY3,P0DP24,P0DP25,P0DP58,P0DP72,P0DP91,P0DPA3,P0DPB3,P0DPB5,P0DPB6,P0DPD7,P0DPD8,P0DPE8,P0DPF2,P0DPF3,P0DPH7,P0DPH8,P0DPI2,P10070,P10071,P10072,P10073,P10074,P10109,P10114,P10124,P10155,P10242,P10243,P10244,P10275,P10276,P10301,P10314,P10316,P10319,P10321,P10398,P10412,P10415,P10451,P10515,P10523,P10586,P10588,P10589,P10599,P10619,P10620,P10632,P10636,P10643,P10644,P10645,P10696,P10721,P10745,P10746,P10747,P10768,P10827,P10912,P10914,P10916,P10966,P11021,P11047,P11055,P11086,P11137,P11142,P11161,P11168,P11169,P11171,P11177,P11182,P11215,P11216,P11217,P11229,P11233,P11234,P11274,P11277,P11279,P11308,P11309,P11310,P11362,P11388,P11413,P11441,P11473,P11474,P11488,P11509,P11532,P11586,P11684,P11686,P11712,P11717,P11766,P11802,P11831,P11836,P11908,P11912,P12004,P12035,P12036,P12074,P12081,P12107,P12109,P12110,P12111,P12235,P12236,P12259,P12268,P12270,P12271,P12272,P12277,P12314,P12318,P12429,P12524,P12532,P12643,P12644,P12645,P12694,P12724,P12755,P12757,P12814,P12821,P12830,P12872,P12882,P12883,P12931,P12955,P12980,P13010,P13051,P13056,P13073,P13164,P13196,P13224,P13378,P13489,P13498,P13521,P13533,P13535,P13569,P13584,P13591,P13611,P13612,P13631,P13637,P13639,P13640,P13645,P13646,P13647,P13667,P13674,P13682,P13686,P13688,P13693,P13716,P13726,P13746,P13747,P13760,P13761,P13762,P13765,P13796,P13797,P13804,P13805,P13861,P13866,P13928,P13929,P13984,P13994,P13995,P14136,P14138,P14174,P14207,P14209,P14314,P14316,P14324,P14415,P14416,P14543,P14550,P14618,P14621,P14625,P14635,P14649,P14651,P14652,P14672,P14735,P14778,P14780,P14784,P14854,P14859,P14867,P14868,P14921,P14923,P15018,P15036,P15056,P15090,P15104,P15144,P15151,P15153,P15170,P15172,P15259,P15260,P15291,P15311,P15313,P15336,P15374,P15391,P15407,P15408,P15428,P15498,P15509,P15529,P15531,P15559,P15586,P15622,P15735,P15814,P15822,P15848,P15863,P15882,P15884,P15907,P15923,P15924,P15927,P15941,P15954,P15976,P16050,P16070,P16083,P16104,P16109,P16112,P16118,P16144,P16150,P16152,P16157,P16188,P16189,P16190,P16219,P16220,P16284,P16333,P16383,P16389,P16401,P16402,P16403,P16415,P16435,P16452,P16455,P16471,P16473,P16519,P16581,P16591,P16662,P16870,P16871,P16885,P16930,P16949,P16989,P17010,P17014,P17017,P17020,P17022,P17023,P17025,P17026,P17027,P17028,P17029,P17031,P17032,P17035,P17036,P17038,P17040,P17041,P17096,P17097,P17098,P17152,P17174,P17181,P17252,P17301,P17302,P17342,P17480,P17481,P17483,P17509,P17516,P17535,P17540,P17542,P17544,P17568,P17600,P17655,P17658,P17661,P17676,P17677,P17706,P17707,P17735,P17752,P17787,P17812,P17813,P17844,P17858,P17861,P17927,P17931,P17936,P17947,P17948,P17987,P18031,P18065,P18074,P18077,P18084,P18085,P18089,P18124,P18146,P18206,P18283,P18433,P18440,P18462,P18463,P18464,P18465,P18505,P18510,P18564,P18583,P18615,P18621,P18627,P18669,P18754,P18827,P18846,P18847,P18848,P18850,P18858,P18887,P19012,P19021,P19022,P19086,P19087,P19105,P19113,P19174,P19237,P19320,P19338,P19367,P19387,P19388,P19404,P19419,P19438,P19447,P19474,P19525,P19532,P19544,P19622,P19623,P19634,P19652,P19784,P19793,P19801,P19823,P19827,P19838,P19878,P19957,P19971,P20020,P20023,P20039,P20042,P20073,P20132,P20138,P20231,P20248,P20264,P20265,P20273,P20290,P20309,P20333,P20336,P20337,P20338,P20339,P20340,P20366,P20393,P20396,P20472,P20585,P20591,P20594,P20618,P20648,P20671,P20674,P20700,P20701,P20711,P20719,P20749,P20794,P20810,P20813,P20827,P20839,P20849,P20853,P20908,P20929,P20930,P20941,P20962,P20963,P21108,P21127,P21128,P21246,P21266,P21281,P21283,P21291,P21333,P21359,P21399,P21439,P21452,P21453,P21462,P21549,P21554,P21579,P21580,P21583,P21675,P21695,P21709,P21728,P21730,P21731,P21757,P21796,P21802,P21810,P21815,P21817,P21854,P21912,P21917,P21918,P21926,P21964,P22001,P22033,P22059,P22061,P22079,P22090,P22102,P22105,P22223,P22234,P22307,P22310,P22314,P22362,P22392,P22415,P22455,P22459,P22460,P22466,P22492,P22528,P22531,P22532,P22570,P22607,P22612,P22626,P22670,P22674,P22676,P22680,P22681,P22692,P22694,P22695,P22732,P22735,P22748,P22760,P22792,P22794,P22897,P23025,P23109,P23142,P23229,P23246,P23258,P23276,P23284,P23297,P23327,P23352,P23381,P23396,P23434,P23443,P23458,P23467,P23468,P23469,P23471,P23497,P23508,P23511,P23515,P23526,P23527,P23528,P23588,P23634,P23743,P23760,P23763,P23769,P23771,P23919,P23921,P24001,P24043,P24278,P24298,P24385,P24386,P24394,P24468,P24534,P24539,P24588,P24593,P24723,P24752,P24821,P24844,P24863,P24864,P24928,P24941,P25021,P25025,P25054,P25089,P25090,P25098,P25101,P25103,P25106,P25116,P25205,P25208,P25325,P25391,P25398,P25440,P25445,P25490,P25685,P25686,P25713,P25786,P25787,P25788,P25789,P25791,P25929,P25940,P25963,P26006,P26010,P26012,P26038,P26045,P26232,P26358,P26367,P26368,P26373,P26374,P26378,P26439,P26440,P26447,P26583,P26599,P26639,P26640,P26651,P26678,P26842,P26951,P26998,P27037,P27105,P27144,P27216,P27338,P27348,P27352,P27361,P27448,P27482,P27540,P27544,P27635,P27694,P27695,P27707,P27708,P27815,P27816,P27824,P27986,P27987,P28062,P28065,P28066,P28068,P28070,P28072,P28074,P28161,P28222,P28288,P28290,P28300,P28324,P28329,P28330,P28331,P28332,P28340,P28347,P28356,P28358,P28360,P28370,P28472,P28482,P28562,P28698,P28702,P28715,P28749,P28799,P28827,P28838,P28906,P28908,P29033,P29034,P29074,P29083,P29084,P29120,P29144,P29218,P29274,P29317,P29320,P29322,P29323,P29350,P29371,P29372,P29373,P29374,P29375,P29400,P29401,P29466,P29475,P29508,P29558,P29590,P29597,P29692,P29728,P29762,P29803,P29966,P29992,P30038,P30039,P30040,P30041,P30044,P30046,P30048,P30050,P30084,P30085,P30086,P

In [33]:
mapping = pd.read_csv('../data/deepmvp/idmapping_2026_04_27_train.tsv', sep='\t')
joined = grouped.join(mapping.set_index('From'), how='right')
joined

,aa,pos,x,y,Entry,Entry Name,Sequence
A0A024RBG1,"[S, S]","[149, 159]",[EWFKVEDAIKVLQCHKPVHAEYLEKLKLGCSPANGNSTVPSLPDN...,"[1, 1]",A0A024RBG1,NUD4B_HUMAN,MMKFKPNQTRTYDREGFKKRAACLCFRSEQEDEVLLVSSSRYPDQW...
A0A075B6I4,[S],[83],[AAWLQQHQGHPPKLLSYRNNNRPSGISERFSASRSGNTASLTITG...,[1],A0A075B6I4,LVX54_HUMAN,MPWALLLLTLLTHSAVSVVQAGLTQPPSVSKGLRQTATLTCTGNSN...
A0A075B767,"[T, T]","[68, 119]",[ALSTGEKGFRYKGSCFHRIIPGFMCQGGDFTRPNGTDDKSIYGEK...,"[1, 1]",A0A075B767,PAL4H_HUMAN,MVNSVVFFDITVDGKPLGRISIKLFADKIPKTAENFRALSTGEKGF...
A0A096LP49,"[S, S, S, S, S, S, S, S, S, S, S, S, S, S, S, ...","[443, 478, 500, 519, 525, 566, 592, 633, 635, ...",[CCRDPNAQSSFSKSPWAMTERKHSSLERARSVHTWEPWSSSTARE...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, ...",A0A096LP49,CC187_HUMAN,MPTLVVGTPPTCLGDTPQPCHKNSQRQGPFSHGAPGRAADWKAVAK...
A0A0A0MS14,"[S, S]","[94, 96]",[LEWMGWITPFNGNTNYAQKFQDRVTITRDRSMSTAYMELSSLRSE...,"[1, 1]",A0A0A0MS14,HV145_HUMAN,MDWTWRILFLVAAVTDAYSQMQLVQSGAEVKKTGSSVKVSCKASGY...
...,...,...,...,...,...,...,...
Q9Y6X5,"[T, S]","[70, 439]",[YLKNYEFPHLQNFIKEGVLVEHVKNVFITKTFPNHYSIVTGLYEE...,"[1, 1]",Q9Y6X5,ENPP4_HUMAN,MKLLVILLFSGLITGFRSDSSSSLPPKLLLVSFDGFRADYLKNYEF...
Q9Y6X6,"[S, S, S, S, S, S, S, S, S, S, S, S, S, T, S, ...","[962, 1311, 1316, 1337, 1362, 1367, 1536, 1539...",[FVMKTSENVVINHLFQSKLSQTGSLVSAYPSFKFRGHKSALLSKK...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, ...",Q9Y6X6,MYO16_HUMAN,MEIDQCLLESLPLGQRQRLVKRMRCEQIKAYYEREKAFQKQEGFLK...
Q9Y6Y0,"[S, S, S, S, S, S, T, S, S, T, S, S, S, S, T, ...","[28, 246, 268, 269, 270, 271, 272, 276, 277, 2...",[XXXMIPNGYLMFEDENFIESSVAKLNALRKSGQFCDVRLQVCGHE...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",Q9Y6Y0,NS1BP_HUMAN,MIPNGYLMFEDENFIESSVAKLNALRKSGQFCDVRLQVCGHEMLAH...
Q9Y6Y1,"[S, S, T, S, S, S, S]","[515, 523, 525, 1226, 1266, 1288, 1301]",[PDCFLNNPKQGQTYGGGGLKAEMVSSNIRHSPPGERSFSFTTVLT...,"[1, 1, 1, 1, 1, 1, 1]",Q9Y6Y1,CMTA1_HUMAN,MWRAEGKWLPKTSRKSVSQSVFCGTSTYCVLNTVPPIEDDHGNSNS...
Q9Y6Y8,"[S, S, S, S, S, S, S, S, S, S, S, S, S, S, T, ...","[126, 130, 134, 136, 258, 405, 406, 636, 728, ...",[IGQSPLTTAATSVGQSGFPKPLTALPFTTGSQDVSNAFSPSISKA...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",Q9Y6Y8,S23IP_HUMAN,MAERKPNGGSGGASTSSSGTNLLFSSSATEFSFNVPFIPVTQASAS...

Some mismatches in the ids..

In [34]:
(joined.Entry != joined.index).sum()

np.int64(78)

In [35]:
joined = joined.rename(columns={'From' : 'id', 'pos' : 'sites', 'y' : 'labels', 'Sequence' : 'sequence'})

In [36]:
joined[joined.index.duplicated(keep=False)]

,aa,sites,x,labels,Entry,Entry Name,sequence
P01562,"[S, S]","[50, 176]",[CSLGCDLPETHSLDNRRTLMLLAQMSRISPSSCLMDRHDFGFPQE...,"[1, 1]",A0A087WWS6,IFNAD_HUMAN,MMASPFALLMALVVLSCKSSCSLGCDLPETHSLDNRRTLMLLAQMS...
P01562,"[S, S]","[50, 176]",[CSLGCDLPETHSLDNRRTLMLLAQMSRISPSSCLMDRHDFGFPQE...,"[1, 1]",P0DY56,IFNA1_HUMAN,MASPFALLMVLVVLSCKSSCSLGCDLPETHSLDNRRTLMLLAQMSR...
Q13065,[T],[40],[YWPRPRRYVQPPEMIGPMRPEQFSDEVEPATPEEGEPATQRQDPA...,[1],P0DSO3,GAGE4_HUMAN,MSWRGRSTYYWPRPRRYVQPPEMIGPMRPEQFSDEVEPATPEEGEP...
Q13065,[T],[40],[YWPRPRRYVQPPEMIGPMRPEQFSDEVEPATPEEGEPATQRQDPA...,[1],P0DTW1,GAGE1_HUMAN,MSWRGRSTYYWPRPRRYVQPPEMIGPMRPEQFSDEVEPATPEEGEP...
Q13068,"[T, S]","[40, 115]",[YWPRPRRYVQPPEMIGPMRPEQFSDEVEPATPEEGEPATQRQDPA...,"[1, 1]",P0DSO3,GAGE4_HUMAN,MSWRGRSTYYWPRPRRYVQPPEMIGPMRPEQFSDEVEPATPEEGEP...
Q13068,"[T, S]","[40, 115]",[YWPRPRRYVQPPEMIGPMRPEQFSDEVEPATPEEGEPATQRQDPA...,"[1, 1]",P0DTW1,GAGE1_HUMAN,MSWRGRSTYYWPRPRRYVQPPEMIGPMRPEQFSDEVEPATPEEGEP...
Q6ZMK1,[S],[137],[QATCPNCRCEISKSLCCRNLAVEKAVSELPSECGFCLRQFPRSLL...,[1],P0DTL5,TM276_HUMAN,MAPKPGAEWSTALSHLVLGVVSLHAAVSTAEASRGAAAGFLLQVLA...
Q6ZMK1,[S],[137],[QATCPNCRCEISKSLCCRNLAVEKAVSELPSECGFCLRQFPRSLL...,[1],P0DTL6,ZTRF1_HUMAN,MSGAEEAGGGGPAAGPAGSVPAGVGVGVGAGPGAAAGQAAAAALGE...

In [37]:
joined['id'] = joined.index

In [ ]:
temp_info = joined[['id', 'sites', 'labels', 'sequence']]

In [ ]:
temp_info['original_label'] = 'train'

C:\Users\Samo\AppData\Local\Temp\ipykernel_15892\3287061273.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_info['original_label'] = 'train'

In [ ]:
temp_info['sites'] = temp_info.apply(filter_fn, axis=1)

C:\Users\Samo\AppData\Local\Temp\ipykernel_15892\2255791578.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_info['sites'] = train_info.apply(filter_fn, axis=1)

In [ ]:
temp_info

,id,sites,labels,sequence,original_label
A0A024RBG1,A0A024RBG1,"[149, 159]","[1, 1]",MMKFKPNQTRTYDREGFKKRAACLCFRSEQEDEVLLVSSSRYPDQW...,train
A0A075B6I4,A0A075B6I4,[83],[1],MPWALLLLTLLTHSAVSVVQAGLTQPPSVSKGLRQTATLTCTGNSN...,train
A0A075B767,A0A075B767,"[68, 119]","[1, 1]",MVNSVVFFDITVDGKPLGRISIKLFADKIPKTAENFRALSTGEKGF...,train
A0A096LP49,A0A096LP49,"[443, 478, 500, 519, 525, 566, 592, 633, 635, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, ...",MPTLVVGTPPTCLGDTPQPCHKNSQRQGPFSHGAPGRAADWKAVAK...,train
A0A0A0MS14,A0A0A0MS14,"[94, 96]","[1, 1]",MDWTWRILFLVAAVTDAYSQMQLVQSGAEVKKTGSSVKVSCKASGY...,train
...,...,...,...,...,...
Q9Y6X5,Q9Y6X5,"[70, 439]","[1, 1]",MKLLVILLFSGLITGFRSDSSSSLPPKLLLVSFDGFRADYLKNYEF...,train
Q9Y6X6,Q9Y6X6,"[962, 1311, 1316, 1337, 1362, 1367, 1536, 1539...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, ...",MEIDQCLLESLPLGQRQRLVKRMRCEQIKAYYEREKAFQKQEGFLK...,train
Q9Y6Y0,Q9Y6Y0,"[28, 246, 268, 269, 270, 271, 272, 276, 277, 2...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",MIPNGYLMFEDENFIESSVAKLNALRKSGQFCDVRLQVCGHEMLAH...,train
Q9Y6Y1,Q9Y6Y1,"[515, 523, 525, 1226, 1266, 1288, 1301]","[1, 1, 1, 1, 1, 1, 1]",MWRAEGKWLPKTSRKSVSQSVFCGTSTYCVLNTVPPIEDDHGNSNS...,train
Q9Y6Y8,Q9Y6Y8,"[126, 130, 134, 136, 258, 405, 406, 636, 728, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",MAERKPNGGSGGASTSSSGTNLLFSSSATEFSFNVPFIPVTQASAS...,train

In [ ]:
total_info = pd.concat([temp_info.drop(columns='labels'), temp_info.drop(columns='labels')])

In [43]:
total_info

,id,sites,sequence,original_label
A0A024RBG1,A0A024RBG1,"[149, 159]",MMKFKPNQTRTYDREGFKKRAACLCFRSEQEDEVLLVSSSRYPDQW...,train
A0A075B6I4,A0A075B6I4,[83],MPWALLLLTLLTHSAVSVVQAGLTQPPSVSKGLRQTATLTCTGNSN...,train
A0A075B767,A0A075B767,"[68, 119]",MVNSVVFFDITVDGKPLGRISIKLFADKIPKTAENFRALSTGEKGF...,train
A0A096LP49,A0A096LP49,"[443, 478, 500, 519, 525, 566, 592, 633, 635, ...",MPTLVVGTPPTCLGDTPQPCHKNSQRQGPFSHGAPGRAADWKAVAK...,train
A0A0A0MS14,A0A0A0MS14,"[94, 96]",MDWTWRILFLVAAVTDAYSQMQLVQSGAEVKKTGSSVKVSCKASGY...,train
...,...,...,...,...
Q9Y6A5,Q9Y6A5,"[2, 12, 25, 39, 56, 59, 71, 73, 87, 133, 138, ...",MSLQVLNDKNVSNEKNTENCDFLFSPPEVTGRSSVLRVSQKENVPP...,test
Q9Y6P5,Q9Y6P5,"[313, 314]",MRLAAAANEAYTAPLAVSGLLGCKQCGGGRDQDEELGIRIPRPLGQ...,test
Q9Y6R0,Q9Y6R0,"[215, 224, 228, 251, 263, 265, 268, 269, 270, ...",MSRSAAASGGPRRPERHLPPAPCGAPGPPETCRTEPDGAGTMNKLR...,test
Q9Y6R9,Q9Y6R9,"[106, 170, 273, 274, 285, 334, 336, 338, 373, ...",MDQPAGLQVDYVFRGVEHAVRVMVSGQVLELEVEDRMTADQWRGEF...,test
Q9Y6X8,Q9Y6X8,"[37, 54, 55, 207, 439, 578, 624, 625, 628, 630...",MASKRKSTTPCMVRTSQVVEQDVPEEVDRAKEKGIGTPQPDVAKDS...,test

There are some duplicates present

In [44]:
total_info[total_info.index.duplicated(keep=False)]

,id,sites,sequence,original_label
P01562,P01562,"[50, 176]",MMASPFALLMALVVLSCKSSCSLGCDLPETHSLDNRRTLMLLAQMS...,train
P01562,P01562,"[50, 176]",MASPFALLMVLVVLSCKSSCSLGCDLPETHSLDNRRTLMLLAQMSR...,train
Q13065,Q13065,[40],MSWRGRSTYYWPRPRRYVQPPEMIGPMRPEQFSDEVEPATPEEGEP...,train
Q13065,Q13065,[40],MSWRGRSTYYWPRPRRYVQPPEMIGPMRPEQFSDEVEPATPEEGEP...,train
Q13068,Q13068,"[40, 115]",MSWRGRSTYYWPRPRRYVQPPEMIGPMRPEQFSDEVEPATPEEGEP...,train
Q13068,Q13068,"[40, 115]",MSWRGRSTYYWPRPRRYVQPPEMIGPMRPEQFSDEVEPATPEEGEP...,train
Q6ZMK1,Q6ZMK1,[137],MAPKPGAEWSTALSHLVLGVVSLHAAVSTAEASRGAAAGFLLQVLA...,train
Q6ZMK1,Q6ZMK1,[137],MSGAEEAGGGGPAAGPAGSVPAGVGVGVGAGPGAAAGQAAAAALGE...,train

In [45]:
total_info = total_info[~total_info.index.duplicated()]

There are some missing sequences

In [55]:
total_info[total_info['sequence'].isna()]

,id,sites,sequence,original_label
A0A0B4J2F2,A0A0B4J2F2,"[186, 435, 437, 438, 473, 516, 534, 575, 626, ...",NaN,train
A8MVS1,A8MVS1,[103],NaN,train
O60361,O60361,"[79, 84, 105, 107, 110]",NaN,train
P0C842,P0C842,"[108, 113, 114]",NaN,train
P0DN24,P0DN24,"[39, 42, 60, 78]",NaN,train
P0DN79,P0DN79,"[27, 32, 61, 63, 73, 199]",NaN,train
P0DPE8,P0DPE8,[138],NaN,train
Q12799,Q12799,[236],NaN,train
Q5SRD0,Q5SRD0,"[20, 21, 42, 54, 81, 86, 90, 99, 109, 111, 136...",NaN,train
Q8N7I0,Q8N7I0,[128],NaN,train
Q8NAS9,Q8NAS9,[29],NaN,train
Q8NG57,Q8NG57,"[121, 125]",NaN,train
Q9BZD3,Q9BZD3,"[144, 178, 179, 184, 364, 365]",NaN,train

In [54]:
total_info.dropna().reset_index(drop=True).to_json('../data/deepmvp/deepmvp_info.json', indent=4)

In [59]:
total_info = total_info.dropna().reset_index(drop=True)

In [67]:
from sklearn.model_selection import train_test_split

train, dev = train_test_split(total_info[total_info.original_label == 'train'], test_size=0.1, random_state=42)

In [68]:
splits = []
splits.append({'train' : train.index.to_list(), 'dev' : dev.index.to_list(), 'test' : total_info[total_info.original_label == 'test'].index.to_list()})

In [69]:
import os
import json
out_folder = '../data/deepmvp/'
label = 'ST'
with open(os.path.join(out_folder, f"splits_{label}.json"), 'w') as f:
            json.dump(splits, f, indent='\t')

In [39]:
def match_check_fn(row):
    try:
        return any([row['sequence'][site - 1] != row['aa'][i] for i, site in enumerate(row['sites'])])
    except IndexError:
        # Index out of bounds, remove sequence
        return True

# joined.apply(match_check_fn, axis=1)

# Main part - prot info and splits creation

- We apply the following pre-processing
    - group the DeepMVP data by protein ID
    - Run a UniProt ID mapping to find the full sequences
    - remove mismatched/missing sequences
        - mismatched == sequences where there is at least one window in the original DeepMVP dataset which does not match
        the window extracted from the UniProt ID mapping sequence corresponding to the ID.

    - remove sequences longer than 1022 (ESM-2 limit)

In [73]:
from sklearn.model_selection import train_test_split
import os
import json

def extract_protein_list(path, id_column='protein'):
    df = pd.read_csv(path, sep='\t')
    grouped = df.groupby(id_column).agg(list)
    print(",".join(grouped.index.to_list()))
    return grouped

def remove_long(x, max_len=1022):
      return len(x) > max_len

def prepare_prot_info(test_mapping_path, train_mapping_path, grouped_test_df, grouped_train_df):
    test_data = (test_mapping_path, grouped_test_df, 'test')
    train_data = (train_mapping_path, grouped_train_df, 'train')
    processed_dfs = []
    for map_path, df, label in (test_data, train_data):
        print(f'Label: {label}')
        mapping = pd.read_csv(map_path, sep='\t')
        joined = df.join(mapping.set_index('From'))

        print(f'Updated IDs: {(joined.Entry != joined.index).sum()}')
        print(f'Duplicated IDs: {joined[joined.index.duplicated(keep=False)]}')
        print(f'Missing Sequences: {joined['Sequence'].isna().sum()} {joined[joined['Sequence'].isna()]}')
        joined = joined.dropna()
        joined.index = joined.index.rename('protein')
        joined = joined.reset_index().rename(columns={'protein' : 'id', 'pos' : 'sites', 'y' : 'labels', 'Sequence' : 'sequence'})
        joined = joined[~joined['id'].duplicated()]
        # Remove sequences with invalid labels
        mismatched_mask = joined.apply(match_check_fn, axis=1)
        print(f'Mismatched sequences: {mismatched_mask.sum()}')
        joined = joined.loc[~mismatched_mask]
        temp_info = joined[['id', 'sites', 'labels', 'sequence']]
        temp_info.loc[:, 'original_label'] = label

        if label == 'train':
            # remove sequences that are too long from the training data
            temp_info = temp_info[~temp_info.sequence.apply(remove_long)]
            
        temp_info.loc[:, 'sites'] = temp_info.apply(filter_fn, axis=1)
        processed_dfs.append(temp_info.drop(columns='labels'))
        print()

    return pd.concat(processed_dfs, ignore_index=True)
    

def prepare_splits(prot_info, dev_size=0.1, out_folder='../data/deepmvp/', label='Y'):
    train, dev = train_test_split(prot_info[prot_info.original_label == 'train'].index, test_size=dev_size)
    splits = [{'train' : train.to_list(), 'dev' : dev.to_list(), 'test' : prot_info[prot_info.original_label == 'test'].index.to_list()}]
    with open(os.path.join(out_folder, f"splits_{label}.json"), 'w') as f:
                json.dump(splits, f, indent='\t')

In [78]:
train_y = extract_protein_list('../data/deepmvp/phos_y_training.tsv')

A0A5B6,A0AV96,A0AVF1,A0FGR8,A0JNW5,A0MZ66,A1KXE4,A1L4K1,A1X283,A1XBS5,A2A3N6,A2AJT9,A2RRP1,A2RTX5,A2VDJ0,A4D0S4,A4D161,A5A3E0,A5PKW4,A5PLK6,A5YKK6,A5YM69,A6NC78,A6NCC3,A6NEC2,A6NEL2,A6NEQ2,A6NFR6,A6NHL2,A6NHR9,A6NI28,A6NI72,A6NJZ7,A6NKB5,A6NKD9,A6NKL6,A6NKT7,A6NMD2,A6NMY6,A6NMZ7,A6NNM3,A6NNZ2,A7E2V4,A7E2Y1,A7KAX9,A8CG34,A8MPP1,A8MQ03,A8MQB3,A8MTZ7,A8MVU1,A8MVW0,A8MXV4,A8TX70,A9Z1Z3,B0I1T2,B1AK53,B2RPK0,B2RUZ4,B2RXH2,B5ME19,C9JH25,C9JLW8,C9JQL5,C9JRZ8,D6RF30,E9PAV3,F8WBI6,G9CGD6,H3BQL2,H3BSY2,H3BV12,I6L899,O00116,O00148,O00151,O00154,O00159,O00160,O00161,O00170,O00182,O00186,O00192,O00193,O00203,O00221,O00231,O00233,O00264,O00267,O00299,O00308,O00311,O00329,O00401,O00408,O00410,O00418,O00423,O00425,O00443,O00444,O00459,O00461,O00507,O00515,O00522,O00533,O00534,O00559,O00560,O00562,O00567,O00571,O00592,O00625,O00629,O00712,O00750,O00757,O00762,O00763,O00767,O14490,O14492,O14493,O14494,O14497,O14513,O14514,O14523,O14526,O14531,O14545,O14578,O14617,O14628,O14639,O14640,O14641,O14646,O14654,O14672,O14682,O14684,O14686,O14715,O14730,O14733,O14737,O14744,O14756,O14757,O14777,O14796,O14802,O14818,O14830,O14832,O14874,O14879,O14880,O14896,O14920,O14924,O14939,O14949,O14950,O14958,O14964,O14974,O14976,O14979,O14980,O15013,O15014,O15021,O15031,O15034,O15037,O15042,O15047,O15049,O15061,O15063,O15067,O15075,O15078,O15085,O15116,O15117,O15126,O15143,O15144,O15145,O15155,O15160,O15164,O15173,O15211,O15212,O15226,O15231,O15234,O15239,O15240,O15244,O15264,O15269,O15294,O15327,O15355,O15357,O15360,O15371,O15379,O15400,O15403,O15417,O15431,O15438,O15439,O15440,O15498,O15504,O15516,O15523,O15530,O15533,O15541,O15551,O43143,O43150,O43155,O43164,O43172,O43181,O43182,O43184,O43189,O43236,O43237,O43242,O43252,O43278,O43281,O43290,O43294,O43295,O43298,O43300,O43301,O43303,O43312,O43314,O43318,O43347,O43353,O43379,O43399,O43402,O43488,O43490,O43491,O43516,O43520,O43526,O43566,O43581,O43597,O43602,O43609,O43615,O43639,O43657,O43660,O43663,O43665,O43674,O43677,O43683,O43684,O43699,O43707,O43709,O43719,O43739,O43741,O43747,O43760,O43768,O43776,O43781,O43790,O43795,O43809,O43813,O43815,O43819,O43823,O43826,O43852,O43861,O43896,O43900,O43909,O43914,O43929,O43933,O60237,O60240,O60241,O60242,O60244,O60245,O60268,O60271,O60279,O60292,O60303,O60307,O60313,O60315,O60330,O60333,O60341,O60343,O60346,O60361,O60427,O60437,O60443,O60447,O60481,O60487,O60488,O60493,O60496,O60506,O60516,O60524,O60547,O60566,O60610,O60613,O60637,O60641,O60645,O60658,O60664,O60667,O60674,O60684,O60701,O60711,O60716,O60739,O60749,O60762,O60784,O60828,O60832,O60841,O60884,O60885,O60890,O60934,O75022,O75023,O75044,O75054,O75061,O75081,O75083,O75110,O75113,O75121,O75122,O75128,O75131,O75140,O75151,O75157,O75165,O75167,O75179,O75204,O75223,O75312,O75323,O75330,O75340,O75343,O75347,O75369,O75376,O75380,O75381,O75387,O75390,O75391,O75396,O75419,O75431,O75446,O75462,O75467,O75477,O75478,O75494,O75508,O75509,O75528,O75534,O75553,O75563,O75581,O75582,O75643,O75663,O75665,O75674,O75676,O75688,O75695,O75717,O75746,O75762,O75781,O75783,O75787,O75791,O75792,O75794,O75815,O75817,O75821,O75822,O75830,O75832,O75843,O75874,O75886,O75896,O75934,O75935,O75937,O75940,O75947,O75953,O75955,O75962,O75964,O75970,O75976,O75995,O76039,O76041,O76070,O94762,O94776,O94788,O94804,O94806,O94811,O94819,O94826,O94829,O94832,O94851,O94854,O94856,O94868,O94875,O94880,O94886,O94887,O94900,O94903,O94905,O94906,O94910,O94911,O94915,O94916,O94925,O94929,O94933,O94953,O94964,O94967,O94973,O94979,O94986,O94988,O94991,O95049,O95070,O95071,O95139,O95149,O95159,O95168,O95171,O95197,O95202,O95206,O95218,O95219,O95229,O95235,O95238,O95239,O95248,O95251,O95267,O95297,O95298,O95340,O95342,O95347,O95359,O95361,O95365,O95376,O95400,O95405,O95425,O95429,O95433,O95436,O95453,O95471,O95484,O95487,O95490,O95528,O95551,O95602,O95613,O95619,O95644,O95678,O95684,O95707,O95718,O95721,O95758,O95772,O95782,O95785,O95786,O95801,O95810,O95817,O95819,O95832,O95835,O95847,O95866,O95881,O95905,O95936,O95985,O95994,O95997,O96000,O96013,O96017,O96028,P00325,P00326,P00338,P00352,P00367,P00374,P00390,P00491,P00492,P00505,P00519,P00533,P00558,P00568,P00734,P00747,P00813,P00918,P00966,P01009,P01011,P01023,P01033,P01111,P01116,P01130,P01833,P01859,P01891,P01892,P02144,P02461,P02538,P02545,P02549,P02652,P02671,P02679,P02686,P02751,P02763,P02768,P02775,P02787,P02792,P02794,P04004,P04049,P04075,P04080,P04083,P04114,P04156,P04179,P04181,P04183,P04216,P04259,P04264,P04350,P04406,P04626,P04629,P04632,P04818,P04843,P04899,P04920,P05023,P05060,P05062,P05067,P05089,P05091,P05106,P05109,P05120,P05129,P05141,P05165,P05166,P05186,P05198,P05230,P05387,P05388,P05408,P05452,P05455,P05534,P05546,P05556,P05771,P05783,P05787,P06127,P06132,P06213,P06239,P06241,P06396,P06400,P06493,P06576,P06731,P06732,P06733,P06737,P06748,P06753,P06899,P07099,P07108,P07195,P07196,P07197,P07203,P07205,P07237,P07332,P07355,P07359,P07384,P07437,P07451,P07476,P07477,P07602,P07737,P07741,P07766,P07814,P07910,P07911,P07942,P07947,P07948,P07949,P07951,P08069,P08123,P08133,P08235,P08237,P08238,P08240,P08243,P08247,P08319,P08493,P08559,P08567,P08575,P08581,P08590,P08621,P08631,P08651,P08670,P08697,P08708,P08727,P08729,P08754,P08758,P08779,P08865,P08887,P08910,P08922,P09016,P09017,P09104,P09210,P09211,P09234,P09327,P09382,P09429,P09467,P09493,P09525,P09543,P09564,P09622,P09651,P09661,P09758,P09769,P09874,P09960,P09972,P0C623,P0C870,P0CB38,P0CG38,P0CG39,P0CJ92,P0DJD0,P0DJD1,P0DME0,P0DMV8,P0DMV9,P0DOX7,P0DP23,P0DP24,P0DP25,P0DPB3,P0DPD7,P0DPD8,P0DPH7,P0DPH8,P10155,P10242,P10275,P10316,P10398,P10412,P10451,P10586,P10644,P10721,P10747,P10768,P10809,P11021,P11049,P11055,P11142,P11171,P11172,P11217,P11233,P11234,P11274,P11277,P11279,P11310,P11362,P11387,P11413,P11532,P11586,P11686,P11766,P11802,P11908,P11940,P12036,P12107,P12109,P12235,P12236,P12259,P12268,P12277,P12318,P12429,P12532,P12694,P12814,P12829,P12830,P12882,P12883,P12931,P12955,P12956,P13051,P13073,P13196,P13521,P13533,P13535,P13612,P13637,P13639,P13645,P13646,P13647,P13667,P13686,P13726,P13746,P13796,P13797,P13798,P13804,P13807,P13861,P13928,P13929,P13945,P13984,P13987,P14136,P14314,P14317,P14373,P14406,P14550,P14598,P14618,P14625,P14672,P14784,P14866,P14867,P14868,P14921,P14927,P15056,P15090,P15104,P15121,P15259,P15260,P15311,P15391,P15408,P15498,P15529,P15559,P15622,P15880,P15882,P15884,P15924,P15941,P15954,P16070,P16104,P16109,P16144,P16152,P16220,P16234,P16284,P16333,P16389,P16402,P16403,P16422,P16435,P16444,P16591,P16615,P16885,P16930,P17028,P17066,P17181,P17252,P17480,P17481,P17516,P17540,P17568,P17600,P17612,P17655,P17661,P17676,P17706,P17735,P17812,P17844,P17858,P17931,P17936,P17948,P17980,P18031,P18065,P18077,P18084,P18206,P18433,P18440,P18583,P18621,P18669,P18827,P18887,P19012,P19021,P19022,P19105,P19338,P19367,P19387,P19388,P19404,P19438,P19484,P19623,P19634,P19784,P19793,P19838,P20020,P20023,P20042,P20226,P20231,P20265,P20273,P20309,P20591,P20592,P20618,P20794,P20810,P20916,P20929,P20930,P20941,P20963,P21108,P21291,P21333,P21359,P21397,P21399,P21549,P21579,P21675,P21709,P21796,P21802,P21817,P21860,P21912,P21964,P21980,P22059,P22087,P22102,P22223,P22234,P22307,P22314,P22392,P22413,P22455,P22492,P22532,P22626,P22676,P22681,P22694,P22695,P22760,P23109,P23141,P23142,P23193,P23246,P23352,P23396,P23443,P23458,P23467,P23468,P23469,P23470,P23471,P23508,P23511,P23526,P23527,P23528,P23588,P23634,P23743,P23921,P24001,P24298,P24394,P24534,P24539,P24593,P24666,P24821,P24928,P24941,P25054,P25101,P25106,P25116,P25189,P25325,P25391,P25398,P25440,P25490,P25685,P25705,P25787,P25788,P25789,P25815,P25963,P26006,P26038,P26045,P26196,P26358,P26583,P26599,P26639,P26640,P26641,P27105,P27216,P27338,P27348,P27361,P27448,P27635,P27694,P27695,P27701,P27797,P27816,P27824,P27986,P27987,P28062,P28066,P28070,P28072,P28074,P28161,P28289,P28324,P28331,P28340,P28482,P28702,P28715,P28749,P28827,P28838,P28906,P29083,P29317,P29320,P29323,P29350,P29353,P29374,P29375,P29401,P29474,P29597,P29692,P29803,P29972,P30040,P30041,P30050,P30084,P30085,P30086,P30101,P30153,P30203,P30260,P30273,P30291,P30305,P30307,P30414,P30447,P30457,P30519,P30530,P30533,P30566,P30622,P30711,P30740,P30876,P31040,P31146,P31150,P31153,P31321,P31323,P31327,P31415,P31431,P31483,P31629,P31641,P31689,P31749,P31785,P31939,P31942,P31943,P31946,P31947,P31948,P31949,P31995,P31997,P32004,P32121,P32321,P32754,P32926,P32929,P32942,P32969,P33121,P33151,P33176,P33240,P33241,P33402,P33552,P33991,P34896,P34897,P34931,P34947,P35080,P35221,P35222,P35232,P35236,P35241,P35250,P35251,P35326,P35367,P35414,P35527,P35568,P35573,P35579,P35580,P35590,P35606,P35609,P35611,P35612,P35658,P35680,P35711,P35749,P35900,P35916,P35968,P35998,P36382,P36402,P36543,P36578,P36871,P36897,P36915,P36959,P37108,P37173,P37198,P37268,P37275,P37840,P38117,P38159,P38398,P38432,P38919,P39023,P39687,P39748,P39880,P40121,P40189,P40222,P40227,P40259,P40261,P40337,P40425,P40429,P40763,P40818,P40879,P40937,P40938,P40939,P41091,P41162,P41212,P41223,P41226,P41227,P41236,P41240,P41250,P41252,P41567,P41594,P41732,P41743,P42025,P42166,P42167,P42224,P42226,P42229,P42263,P42330,P42338,P42345,P42356,P42566,P42575,P42677,P42679,P42680,P42681,P42685,P42696,P42768,P42771,P42892,P43004,P43005,P43007,P43034,P43121,P43243,P43358,P43403,P43405,P43487,P43490,P43630,P43686,P43897,P45880,P45954,P45973,P45974,P45983,P45984,P45985,P46013,P46020,P46059,P46063,P46100,P46108,P46109,P46379,P46459,P46531,P46734,P46736,P46776,P46777,P46778,P46781,P46782,P46783,P46821,P46926,P46934,P46939,P46940,P46976,P47712,P47755,P47756,P47813,P47870,P47897,P47929,P47985,P48029,P48047,P48059,P48426,P48443,P48444,P48547,P48551,P48594,P48634,P48637,P48651,P48668,P48681,P48729,P48741,P48751,P48960,P49005,P49023,P49116,P49137,P49189,P49207,P49326,P49327,P49336,P49368,P49407,P49411,P49419,P49454,P49458,P49588,P49589,P49619,P49643,P49674,P49711,P49720,P49721,P49736,P49750,P49755,P49756,P49757,P49759,P49760,P49768,P49773,P49789,P49790,P49792,P49795,P49796,P49815,P49821,P49841,P49914,P49915,P49916,P50222,P50238,P50395,P50402,P50440,P50443,P50452,P50479,P50542,P50548,P50552,P50583,P50613,P50747,P50749,P50750,P50851,P50914,P50991,P50993,P50995,P51116,P51148,P51149,P51151,P51153,P51178,P51451,P51452,P51530,P51587,P51617,P51636,P51659,P51679,P51692,P51797,P51798,P51812,P51813,P51911,P51948,P51955,P51957,P51965,P51970,P51991,P52179,P52209,P52272,P52298,P52306,P52333,P52564,P52565,P52566,P52569,P52594,P52732,P52735,P52747,P52757,P52758,P52799,P52888,P52895,P52907,P52943,P52948,P52952,P53041,P53350,P53396,P53582,P53618,P53621,P53680,P53701,P53778,P53779,P53794,P53801,P53990,P53992,P54105,P54136,P54253,P54257,P54259,P54277,P54284,P54296,P54577,P54578,P54619,P54652,P54753,P54756,P54760,P54762,P54764,P54792,P54819,P54868,P55008,P55010,P55011,P55039,P55072,P55081,P55082,P55085,P55087,P55209,P55265,P55285,P55287,P55327,P55769,P55771,P55786,P55795,P55809,P55884,P55957,P56211,P56470,P56537,P56597,P56747,P56856,P56937,P56945,P57053,P57076,P57682,P57729,P57735,P57737,P57739,P57764,P57768,P58005,P58107,P58317,P58335,P58658,P58876,P59665,P59666,P59768,P60174,P60228,P60660,P60709,P60842,P60891,P60900,P60903,P60981,P61006,P61011,P61019,P61020,P61024,P61026,P61106,P61158,P61244,P61247,P61266,P61289,P61313,P61326,P61353,P61421,P61457,P61586,P61604,P61758,P61764,P61916,P61960,P61978,P61981,P62136,P62140,P62166,P62191,P62195,P62244,P62249,P62258,P62269,P62273,P62277,P62280,P62318,P62333,P62424,P62487,P62491,P62633,P62736,P62745,P62750,P62760,P62805,P62807,P62820,P62826,P62829,P62847,P62851,P62873,P62879,P62888,P62899,P62906,P62913,P62917,P62937,P62955,P62979,P62987,P62993,P62995,P63010,P63096,P63098,P63104,P63167,P63172,P63173,P63220,P63241,P63244,P63261,P63267,P63302,P63316,P67775,P67809,P67870,P68032,P68104,P68133,P68366,P68371,P68400,P68871,P69905,P78310,P78317,P78318,P78325,P78332,P78346,P78347,P78352,P78356,P78362,P78368,P78371,P78386,P78406,P78423,P78424,P78426,P78504,P78527,P78536,P78552,P78559,P80303,P80370,P80723,P81408,P81877,P82094,P82909,P82933,P82970,P83110,P83916,P84022,P84090,P84095,P84103,P84243,P85037,P85298,P85299,P86452,P86791,P98077,P98082,P98171,P98172,P98174,P98175,P98179,P98196,P99999,Q00013,Q00169,Q00341,Q00526,Q00534,Q00535,Q00536,Q00537,Q00587,Q00610,Q00653,Q00839,Q00872,Q008S8,Q00975,Q00987,Q01082,Q01085,Q01101,Q01105,Q01130,Q01196,Q01201,Q01433,Q01469,Q01484,Q01518,Q01543,Q01628,Q01629,Q01780,Q01804,Q01813,Q01814,Q01844,Q01974,Q01995,Q02078,Q02127,Q02156,Q02224,Q02241,Q02252,Q02410,Q02413,Q02487,Q02535,Q02539,Q02543,Q02750,Q02790,Q02818,Q02880,Q02952,Q02978,Q03001,Q03013,Q03111,Q03135,Q03154,Q03188,Q03252,Q03393,Q04206,Q04323,Q04446,Q04637,Q04656,Q04695,Q04721,Q04724,Q04726,Q04727,Q04759,Q04760,Q04828,Q04837,Q04864,Q04900,Q04912,Q04917,Q05048,Q05084,Q05086,Q05193,Q05209,Q05397,Q05513,Q05519,Q05639,Q05655,Q05682,Q05707,Q05BQ5,Q05D32,Q06124,Q06187,Q06190,Q06203,Q06418,Q06481,Q06830,Q07065,Q07157,Q07283,Q07343,Q07617,Q07666,Q07866,Q07890,Q07912,Q07955,Q07960,Q08117,Q08170,Q08174,Q08188,Q08209,Q08211,Q08257,Q08345,Q08357,Q08378,Q08426,Q08495,Q08499,Q08623,Q08945,Q08999,Q08AD1,Q08AE8,Q08AM6,Q09160,Q0JRZ9,Q0VDF9,Q0VF96,Q0ZGT2,Q10567,Q10570,Q10589,Q12768,Q12769,Q12770,Q12774,Q12788,Q12789,Q12792,Q12796,Q12815,Q12830,Q12834,Q12846,Q12849,Q12857,Q12860,Q12872,Q12873,Q12874,Q12888,Q12906,Q12912,Q12913,Q12923,Q12926,Q12929,Q12931,Q12933,Q12948,Q12955,Q12959,Q12965,Q12968,Q12974,Q12979,Q12982,Q12986,Q13009,Q13011,Q13017,Q13029,Q13033,Q13042,Q13043,Q13045,Q13049,Q13057,Q13070,Q13084,Q13085,Q13094,Q13099,Q13103,Q13111,Q13113,Q13115,Q13123,Q13131,Q13136,Q13151,Q13155,Q13164,Q13177,Q13188,Q13190,Q13191,Q13200,Q13201,Q13206,Q13228,Q13232,Q13242,Q13243,Q13247,Q13255,Q13263,Q13283,Q13287,Q13291,Q13303,Q13310,Q13315,Q13322,Q13325,Q13332,Q13347,Q13371,Q13393,Q13416,Q13423,Q13424,Q13426,Q13432,Q13433,Q13435,Q13442,Q13443,Q13449,Q13451,Q13459,Q13464,Q13469,Q13470,Q13480,Q13490,Q13496,Q13501,Q13509,Q13510,Q13523,Q13541,Q13542,Q13546,Q13554,Q13555,Q13561,Q13571,Q13573,Q13574,Q13576,Q13591,Q13595,Q13596,Q13610,Q13615,Q13618,Q13621,Q13625,Q13627,Q13642,Q13671,Q13698,Q13765,Q13772,Q13796,Q13813,Q13822,Q13823,Q13829,Q13835,Q13838,Q13868,Q13873,Q13882,Q13884,Q13885,Q13895,Q13905,Q13946,Q13951,Q13976,Q14004,Q14005,Q14008,Q14011,Q14019,Q14103,Q14108,Q14112,Q14116,Q14118,Q14126,Q14134,Q14137,Q14141,Q14151,Q14152,Q14155,Q14157,Q14160,Q14161,Q14162,Q14165,Q14166,Q14185,Q14191,Q14192,Q14194,Q14195,Q14197,Q14204,Q14232,Q14240,Q14241,Q14242,Q14247,Q14249,Q14254,Q14257,Q14258,Q14289,Q14315,Q14318,Q14320,Q14432,Q14439,Q14444,Q14449,Q14451,Q14498,Q14500,Q14511,Q14515,Q14517,Q14527,Q14533,Q14558,Q14571,Q14574,Q14587,Q14643,Q14644,Q14651,Q14669,Q14671,Q14674,Q14677,Q14678,Q14679,Q14680,Q14683,Q14687,Q14689,Q14691,Q14692,Q14694,Q14697,Q14699,Q14721,Q14738,Q14749,Q14761,Q14764,Q14766,Q14789,Q14790,Q14814,Q14839,Q14847,Q14849,Q14865,Q14872,Q14894,Q14914,Q14929,Q14934,Q14974,Q14978,Q14980,Q14982,Q14C86,Q14CM0,Q14CN4,Q14CS0,Q14CW9,Q14CZ8,Q15003,Q15012,Q15018,Q15019,Q15020,Q15021,Q15029,Q15036,Q15038,Q15042,Q15047,Q15049,Q15056,Q15057,Q15058,Q15059,Q15061,Q15067,Q15072,Q15084,Q15118,Q15124,Q15126,Q15139,Q15149,Q15154,Q15165,Q15173,Q15181,Q15185,Q15208,Q15223,Q15233,Q15262,Q15269,Q15276,Q15286,Q15287,Q15291,Q15293,Q15311,Q15334,Q15349,Q15361,Q15365,Q15366,Q15369,Q15375,Q15389,Q15393,Q15415,Q15417,Q15418,Q15424,Q15427,Q15428,Q15437,Q15438,Q15464,Q15468,Q15555,Q15582,Q155Q3,Q15643,Q15648,Q15650,Q15653,Q15654,Q15661,Q15678,Q15691,Q15700,Q15746,Q15750,Q15751,Q15758,Q15759,Q15760,Q15762,Q15782,Q15785,Q15797,Q15800,Q15811,Q15831,Q15843,Q15849,Q15858,Q15911,Q15942,Q16143,Q16181,Q16204,Q16222,Q16288,Q16352,Q16401,Q16513,Q16531,Q16537,Q16539,Q16540,Q16568,Q16576,Q16594,Q16620,Q16623,Q16625,Q16629,Q16630,Q16643,Q16644,Q16658,Q16659,Q16670,Q16698,Q16720,Q16774,Q16775,Q16778,Q16816,Q16822,Q16836,Q16849,Q16851,Q16875,Q16881,Q16891,Q17R89,Q17RQ9,Q17RS7,Q1ED39,Q1KMD3,Q24JP5,Q2KHM9,Q2KHR3,Q2KJY2,Q2LD37,Q2M218,Q2M2I3,Q2M2I8,Q2M2Z5,Q2M389,Q2M3G4,Q2NKX8,Q2PPJ7,Q2TAA2,Q2TAL8,Q2Y0W8,Q30201,Q32MK0,Q32MZ4,Q32P51,Q3B726,Q3B7T1,Q3KP66,Q3KR37,Q3LXA3,Q3MHD2,Q3SY69,Q3V6T2,Q3YEC7,Q3ZCM7,Q3ZCQ8,Q494U1,Q49A88,Q4AC94,Q4G0N4,Q4KMP7,Q4KMQ1,Q4KWH8,Q4L180,Q4LE39,Q4V321,Q4V326,Q4V9L6,Q4VC44,Q4VCS5,Q4VXU2,Q4ZHG4,Q52LR7,Q52LW3,Q53EL6,Q53ET0,Q53EZ4,Q53F19,Q53FZ2,Q53G59,Q53GD3,Q53GG5,Q53GL0,Q53GS7,Q53HL2,Q53QZ3,Q53RT3,Q53SF7,Q53TN4,Q562R1,Q56P03,Q58A45,Q58DX5,Q58FF6,Q58FF7,Q58FF8,Q5BKX8,Q5BKY9,Q5BKZ1,Q5CZC0,Q5EBL8,Q5F1R6,Q5FBB7,Q5H9R4,Q5HYI8,Q5HYK7,Q5HYW2,Q5J8M3,Q5JPF3,Q5JPH6,Q5JQS6,Q5JRA6,Q5JSH3,Q5JSL3,Q5JSZ5,Q5JTD0,Q5JTV8,Q5JTW2,Q5JWF2,Q5JWR5,Q5M775,Q5MIZ7,Q5MJ10,Q5NDL2,Q5PRF9,Q5QJ74,Q5QJE6,Q5QNW6,Q5R372,Q5R3F8,Q5RHP9,Q5RI15,Q5RKV6,Q5S007,Q5SQ64,Q5SQS7,Q5SSJ5,Q5SW79,Q5SXH7,Q5SYE7,Q5T011,Q5T035,Q5T089,Q5T0N5,Q5T0W9,Q5T0Z8,Q5T1M5,Q5T200,Q5T2T1,Q5T2W1,Q5T3F8,Q5T3J3,Q5T4S7,Q5T5C0,Q5T5P2,Q5T5U3,Q5T5X7,Q5T5Y3,Q5T6F2,Q5T6S3,Q5T7P8,Q5T848,Q5T8I3,Q5T9C2,Q5T9G4,Q5T9L3,Q5T9S5,Q5TA45,Q5TB80,Q5TBA9,Q5TC82,Q5TCX8,Q5TCZ1,Q5TD94,Q5TEJ8,Q5TGI4,Q5TGY3,Q5THJ4,Q5U651,Q5UIP0,Q5VSL9,Q5VST9,Q5VT06,Q5VT25,Q5VT52,Q5VT79,Q5VTT5,Q5VUA4,Q5VUB5,Q5VUG0,Q5VV17,Q5VW32,Q5VWN6,Q5VWP2,Q5VWQ8,Q5VY43,Q5VYS8,Q5VZ18,Q5VZ89,Q5VZK9,Q5VZL5,Q5W0A0,Q5W0Z9,Q5XG87,Q5XKE5,Q5XKK7,Q5XXA6,Q63HQ0,Q63HR2,Q63ZY3,Q641Q2,Q658L1,Q659C4,Q674X7,Q68CK6,Q68CZ2,Q68CZ6,Q68D10,Q68DH5,Q68DQ2,Q68EN5,Q69YQ0,Q6A1A2,Q6AHZ1,Q6AWC2,Q6AZZ1,Q6BDS2,Q6DD87,Q6DN90,Q6DRA6,Q6EKJ0,Q6F5E8,Q6FI81,Q6GQQ9,Q6GTX8,Q6IA17,Q6IAA8,Q6IBS0,Q6IC98,Q6ICB0,Q6ICC9,Q6IE81,Q6IEG0,Q6IQ23,Q6ISB3,Q6KB66,Q6KC79,Q6N022,Q6NSI4,Q6NSJ2,Q6NSZ9,Q6NTF9,Q6NUK4,Q6NUQ4,Q6NV74,Q6NXT2,Q6NYC8,Q6NZI2,Q6P158,Q6P1J9,Q6P1K8,Q6P1L5,Q6P1L8,Q6P1M3,Q6P1N0,Q6P1S2,Q6P2C8,Q6P2H3,Q6P2Q9,Q6P3S1,Q6P3X3,Q6P4E1,Q6P4Q7,Q6P4R8,Q6P587,Q6P597,Q6P5Z2,Q6P6B1,Q6P6C2,Q6P988,Q6P995,Q6P996,Q6PCB5,Q6PCB6,Q6PEY2,Q6PH85,Q6PIF6,Q6PIU2,Q6PIW4,Q6PIY7,Q6PIZ9,Q6PJF5,Q6PJG2,Q6PJT7,Q6PKG0,Q6PL18,Q6Q0C0,Q6Q6R5,Q6QNK2,Q6QNY0,Q6R2W3,Q6R327,Q6RFH5,Q6RI45,Q6RW13,Q6S5L8,Q6S8J3,Q6SJ93,Q6SZW1,Q6T310,Q6T4R5,Q6UB98,Q6UB99,Q6ULP2,Q6UN15,Q6URK8,Q6UUV7,Q6UW02,Q6UWE0,Q6UWF3,Q6UX04,Q6UX71,Q6UXD5,Q6UXG2,Q6UXN9,Q6UXY8,Q6VN20,Q6W2J9,Q6WCQ1,Q6WKZ4,Q6XQN6,Q6XZF7,Q6Y7W6,Q6YHK3,Q6YHU6,Q6ZMT1,Q6ZNC4,Q6ZNJ1,Q6ZNL6,Q6ZRV2,Q6ZS17,Q6ZS30,Q6ZSR9,Q6ZSS7,Q6ZSZ5,Q6ZSZ6,Q6ZT07,Q6ZTA4,Q6ZTI6,Q6ZUI0,Q6ZUJ8,Q6ZUK4,Q6ZUM4,Q6ZV29,Q6ZV50,Q6ZV65,Q6ZV73,Q6ZV89,Q6ZVC0,Q6ZVD7,Q6ZVM7,Q6ZW31,Q6ZW49,Q6ZW76,Q6ZWJ1,Q709C8,Q709F0,Q70CQ4,Q70E73,Q70EK8,Q70EL1,Q70EL4,Q70J99,Q71DI3,Q71F56,Q71H61,Q71RC2,Q71U36,Q71UM5,Q765P7,Q76FK4,Q76N32,Q76N89,Q7KZ85,Q7KZF4,Q7KZI7,Q7L0J3,Q7L1I2,Q7L2E3,Q7L2H7,Q7L3S4,Q7L4I2,Q7L576,Q7L590,Q7L591,Q7L775,Q7L7X3,Q7L804,Q7L8W6,Q7L9L4,Q7LBE3,Q7RTP6,Q7RTT9,Q7RTV3,Q7Z2D5,Q7Z2K8,Q7Z2W4,Q7Z2Y5,Q7Z2Z1,Q7Z3B1,Q7Z3B4,Q7Z3C6,Q7Z3E2,Q7Z3G6,Q7Z3J3,Q7Z3T8,Q7Z402,Q7Z404,Q7Z417,Q7Z422,Q7Z434,Q7Z460,Q7Z4F1,Q7Z4H7,Q7Z4L5,Q7Z4S6,Q7Z4W1,Q7Z569,Q7Z572,Q7Z591,Q7Z5G4,Q7Z5K2,Q7Z5L2,Q7Z5R6,Q7Z698,Q7Z699,Q7Z6B7,Q7Z6E9,Q7Z6G8,Q7Z6I6,Q7Z6J2,Q7Z6K5,Q7Z6M3,Q7Z6P3,Q7Z6Z7,Q7Z7A3,Q7Z7C8,Q7Z7E8,Q7Z7F0,Q7Z7F7,Q7Z7G8,Q86SE9,Q86SQ0,Q86SQ4,Q86SQ6,Q86SU0,Q86T24,Q86T90,Q86TB9,Q86TC9,Q86TD4,Q86TI0,Q86TV6,Q86TW2,Q86U06,Q86U70,Q86U86,Q86U90,Q86UB2,Q86UD0,Q86UE4,Q86UE8,Q86UK7,Q86UL8,Q86UP2,Q86UP8,Q86US8,Q86UU1,Q86UW6,Q86UW9,Q86UX7,Q86UY5,Q86V15,Q86V81,Q86VE9,Q86VI3,Q86VI4,Q86VM9,Q86VP1,Q86VP6,Q86VQ0,Q86VQ1,Q86VS8,Q86VX9,Q86VY9,Q86W33,Q86W56,Q86W92,Q86WG5,Q86WH2,Q86WR0,Q86WR7,Q86WT1,Q86WV1,Q86X10,Q86X27,Q86X29,Q86X76,Q86X95,Q86XI2,Q86XK2,Q86XL3,Q86XN8,Q86XP1,Q86XP3,Q86XR8,Q86XZ4,Q86Y07,Q86Y39,Q86YF9,Q86YL5,Q86YQ8,Q86YR5,Q86YS7,Q86YT9,Q86YV5,Q86YV9,Q86YW5,Q86Z02,Q8IU60,Q8IU85,Q8IUC4,Q8IUD2,Q8IUH3,Q8IV01,Q8IV03,Q8IV08,Q8IV33,Q8IV45,Q8IV48,Q8IV50,Q8IVB4,Q8IVF2,Q8IVH8,Q8IVL1,Q8IVM0,Q8IVT2,Q8IVY1,Q8IW00,Q8IW35,Q8IW45,Q8IW50,Q8IWA5,Q8IWB9,Q8IWC1,Q8IWI9,Q8IWR0,Q8IWS0,Q8IWU2,Q8IWV1,Q8IWW6,Q8IWX8,Q8IWZ3,Q8IWZ6,Q8IWZ8,Q8IX01,Q8IX03,Q8IX12,Q8IX19,Q8IX21,Q8IX90,Q8IXI2,Q8IXJ6,Q8IXK0,Q8IXM2,Q8IXS8,Q8IXT1,Q8IXT5,Q8IXW5,Q8IXZ2,Q8IY21,Q8IY22,Q8IY33,Q8IY63,Q8IY81,Q8IY95,Q8IYB7,Q8IYJ3,Q8IYL2,Q8IYU8,Q8IYW5,Q8IYX8,Q8IZ07,Q8IZ21,Q8IZ69,Q8IZD4,Q8IZH2,Q8IZJ1,Q8IZL9,Q8IZP0,Q8IZQ1,Q8IZR5,Q8IZT6,Q8IZW8,Q8N0X7,Q8N0Y7,Q8N108,Q8N122,Q8N126,Q8N128,Q8N157,Q8N1F7,Q8N1G0,Q8N1G2,Q8N1G4,Q8N1I0,Q8N257,Q8N292,Q8N2F6,Q8N2G6,Q8N300,Q8N392,Q8N3C0,Q8N3D4,Q8N3F8,Q8N3J6,Q8N3P4,Q8N3R9,Q8N3U4,Q8N3V7,Q8N3X1,Q8N423,Q8N441,Q8N488,Q

In [79]:
test_y = extract_protein_list('../data/deepmvp/phos_y_testing_70.tsv')

A2RU30,A6NIX2,A7MD48,O00321,O00453,O00499,O14530,O14544,O14647,O14662,O14668,O14786,O14828,O14917,O14966,O14983,O15020,O15027,O15056,O15197,O15229,O15270,O15344,O15389,O15397,O43166,O43390,O43426,O43561,O43688,O43708,O43734,O43865,O60218,O60291,O60662,O60869,O60883,O60927,O75063,O75112,O75116,O75145,O75190,O75264,O75319,O75461,O75521,O75533,O75575,O76031,O76054,O94885,O94889,O94898,O94921,O95208,O95295,O95372,O95391,O95757,O95793,O95900,P00167,P00387,P00740,P01106,P01112,P01857,P02730,P02786,P02788,P04040,P04150,P04234,P04792,P06744,P07306,P07738,P07900,P07954,P09619,P09669,P09693,P10636,P11137,P11216,P11831,P11912,P14923,P15374,P15407,P15428,P16157,P16471,P17036,P17174,P17302,P17987,P18615,P19174,P19525,P20073,P20393,P20648,P20936,P21127,P22001,P22459,P24752,P25205,P27540,P28290,P29218,P30047,P31751,P33527,P33981,P33993,P34932,P35637,P35869,P36639,P36954,P37802,P38646,P40925,P40926,P41182,P42336,P42684,P42694,P43003,P43246,P46937,P48147,P49279,P49321,P49642,P49761,P50226,P50416,P50453,P50990,P51114,P51580,P52597,P52756,P54727,P55196,P55198,P55317,P56270,P56277,P61086,P61163,P62081,P62241,P62263,P63000,P63092,P78324,P78344,P78524,P84157,P98164,P98170,Q00325,Q00796,Q01546,Q01968,Q01970,Q01973,Q02153,Q02763,Q02878,Q06520,Q08380,Q08881,Q09666,Q12851,Q12866,Q13153,Q13224,Q13370,Q13418,Q13439,Q13467,Q13485,Q14168,Q14526,Q14566,Q14592,Q14765,Q14966,Q15027,Q15032,Q15043,Q15052,Q15303,Q15459,Q15637,Q15652,Q15717,Q15773,Q16512,Q16543,Q16555,Q16650,Q16666,Q16832,Q1EHB4,Q1MSJ5,Q3SXY8,Q53RE8,Q58FG0,Q5D1E8,Q5HYJ3,Q5JU85,Q5JUK2,Q5TBK1,Q5VV41,Q5VZP5,Q68D51,Q69YZ2,Q6BCY4,Q6DN12,Q6EMB2,Q6H8Q1,Q6JBY9,Q6JQN1,Q6NUK1,Q6P0N0,Q6P1R3,Q6PHR2,Q6TGC4,Q6UUV9,Q6UXK2,Q6UXM1,Q6UXY1,Q6VY07,Q6ZTN6,Q6ZWB6,Q70CQ2,Q70Z53,Q7L014,Q7L266,Q7L7V1,Q7M4L6,Q7Z2T5,Q7Z3K3,Q7Z478,Q7Z5N4,Q86UR5,Q86V48,Q86VN1,Q86VQ6,Q86XX4,Q8IUH4,Q8IUH5,Q8IUQ0,Q8IV77,Q8IVI9,Q8IVP5,Q8IW52,Q8IXQ6,Q8IXS6,Q8IY18,Q8IYA6,Q8IYS1,Q8IZP2,Q8N103,Q8N2Y8,Q8N335,Q8N350,Q8N3E9,Q8N5C8,Q8N8S7,Q8N9R8,Q8NAP3,Q8NCA5,Q8NDZ2,Q8NEL9,Q8NEM0,Q8NFH8,Q8NG08,Q8NH16,Q8NHQ1,Q8NI22,Q8TAD4,Q8TAG9,Q8TDQ1,Q8TE99,Q8WU20,Q8WUI4,Q8WUY3,Q8WV92,Q8WVP7,Q8WVV4,Q8WWW0,Q8WXI7,Q8WXI9,Q92508,Q92538,Q92560,Q92581,Q92665,Q92738,Q92823,Q92905,Q96A65,Q96B97,Q96BJ8,Q96BY7,Q96C10,Q96C19,Q96C90,Q96D46,Q96DG6,Q96EK4,Q96GP6,Q96GY3,Q96I24,Q96IG2,Q96IZ5,Q96JW4,Q96KG9,Q96L34,Q96M96,Q96MK2,Q96N67,Q96PK6,Q96PY5,Q96PY6,Q96QE2,Q96RS0,Q96SL8,Q99447,Q99536,Q99541,Q99590,Q99592,Q99598,Q99640,Q99816,Q9BPX3,Q9BRR3,Q9BSJ2,Q9BT67,Q9BUZ4,Q9BXJ9,Q9BXM7,Q9BXS4,Q9BY67,Q9BYD1,Q9BYG3,Q9BYT3,Q9C004,Q9C0D6,Q9C0H9,Q9C0K0,Q9GZN8,Q9H1V8,Q9H4B6,Q9H5V8,Q9H6F5,Q9H6R7,Q9H6T3,Q9H857,Q9H9R9,Q9HAU0,Q9HC35,Q9HCE0,Q9HCE6,Q9HCH0,Q9HCK4,Q9HCK8,Q9HD40,Q9NNW7,Q9NP80,Q9NQR1,Q9NQR4,Q9NQZ5,Q9NR09,Q9NR50,Q9NRA8,Q9NRD1,Q9NRL2,Q9NRX4,Q9NRY4,Q9NSG2,Q9NSI8,Q9NSV4,Q9NUD5,Q9NUP1,Q9NVD7,Q9NVE7,Q9NVH0,Q9NX05,Q9NXH9,Q9NXR1,Q9NYJ8,Q9NYL2,Q9NZ63,Q9NZJ0,Q9NZN8,Q9P1Y6,Q9P242,Q9P244,Q9P258,Q9P2E7,Q9P2M4,Q9P2T1,Q9UBS0,Q9UBS9,Q9UBU7,Q9UDY2,Q9UGN4,Q9UHB6,Q9UHI5,Q9UHK0,Q9UKA2,Q9UKE5,Q9UKK9,Q9UKN7,Q9UKZ1,Q9ULD2,Q9ULF5,Q9ULJ8,Q9ULL5,Q9ULT8,Q9UM73,Q9UMS6,Q9UN70,Q9UNH7,Q9UNZ2,Q9UPY5,Q9UQB8,Q9UQP3,Q9Y243,Q9Y285,Q9Y2E8,Q9Y2L6,Q9Y314,Q9Y3A3,Q9Y3B8,Q9Y3P8,Q9Y3S1,Q9Y3S2,Q9Y485,Q9Y4F5,Q9Y4G8,Q9Y5A7,Q9Y5S2,Q9Y6D9,Q9Y6E0

In [80]:
test_mapping_path = '../data/deepmvp/test_y.tsv'
train_mapping_path = '../data/deepmvp/train_y.tsv'

In [81]:
prot_info = prepare_prot_info(test_mapping_path, train_mapping_path, test_y, train_y)

Label: test
Updated IDs: 1
Duplicated IDs: Empty DataFrame
Columns: [aa, pos, x, y, Entry, Reviewed, Entry Name, Sequence]
Index: []
Missing Sequences: 0 Empty DataFrame
Columns: [aa, pos, x, y, Entry, Reviewed, Entry Name, Sequence]
Index: []
Mismatched sequences: 11

Label: train
Updated IDs: 8
Duplicated IDs: Empty DataFrame
Columns: [aa, pos, x, y, Entry, Reviewed, Entry Name, Sequence]
Index: []
Missing Sequences: 2           aa     pos                                                  x    y  \
protein
A9Z1Z3   [Y]  [1360]  [IGETHIDLENRFYSHHRANCGLASQYEVDGYNAWRDAFWPSQILA...  [1]
O60361   [Y]    [37]  [GKIIKRFEQKGFRLVAMKFLPASEEHLKQHYIDLKDRPFFPGLVK...  [1]

          Entry Reviewed   Entry Name Sequence
protein
A9Z1Z3   A9Z1Z3      NaN  FR1L4_HUMAN      NaN
O60361   O60361      NaN   NDK8_HUMAN      NaN

C:\Users\Samo\AppData\Local\Temp\ipykernel_28428\2953211020.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_info.loc[:, 'original_label'] = label

Mismatched sequences: 68

C:\Users\Samo\AppData\Local\Temp\ipykernel_28428\2953211020.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_info.loc[:, 'original_label'] = label

In [82]:
prepare_splits(prot_info, label='Y')
prot_info.to_json('../data/deepmvp/deepmvp_info_Y.json', indent=4)

In [83]:
prot_info.index[-1]

3882

In [84]:
train_st = extract_protein_list('../data/deepmvp/phos_st_training.tsv')
test_st = extract_protein_list('../data/deepmvp/phos_st_testing_70.tsv')
test_mapping_path = '../data/deepmvp/test_st.tsv'
train_mapping_path = '../data/deepmvp/train_st.tsv'

A0A024RBG1,A0A075B6I4,A0A075B767,A0A096LP49,A0A0A0MS14,A0A0B4J266,A0A0B4J279,A0A0B4J2A2,A0A0B4J2F0,A0A0B4J2F2,A0A0J9YX94,A0A0J9YY54,A0A0U1RRE5,A0A0U1RRI6,A0A0U1RRK4,A0A1B0GTK4,A0A1B0GTU1,A0A1B0GUA9,A0A1B0GUC4,A0A1B0GUJ8,A0A1B0GV03,A0A1B0GVQ0,A0A1B0GVZ6,A0A1B0GWB2,A0A1B0GWG4,A0A2R8YCJ5,A0A5B6,A0AUZ9,A0AV02,A0AV96,A0AVI2,A0AVK6,A0AVT1,A0FGR8,A0FGR9,A0JLT2,A0PJW6,A0PJW8,A0PJX4,A0PJY2,A0PK00,A0PK05,A1A4G5,A1A4S6,A1A5C7,A1IGU5,A1KXE4,A1L020,A1L0T0,A1L162,A1L168,A1L170,A1L188,A1L390,A1L429,A1L4H1,A1X283,A1XBS5,A1YPR0,A2A288,A2A2V5,A2A2Y4,A2A3K4,A2A3N6,A2AJT9,A2IDD5,A2RRD8,A2RRP1,A2RTX5,A2RU30,A2RU54,A2RU67,A2RUB1,A2RUB6,A2RUR9,A2RUS2,A2VCK2,A2VDF0,A3KMH1,A3KN83,A4D126,A4D161,A4D1S0,A4D1S5,A4D1U4,A4D2B0,A4D2H0,A4D2P6,A4FU01,A4FU28,A4FU49,A4FU69,A4QPH2,A4UGR9,A5A3E0,A5D6W6,A5D8V6,A5D8V7,A5PKW4,A5PLN7,A5PLN9,A5YKK6,A5YM69,A5YM72,A6BM72,A6H8M9,A6H8Y1,A6NC57,A6NC78,A6NCC3,A6NCI8,A6NCQ9,A6NCS4,A6NCS6,A6ND36,A6ND91,A6NDB9,A6NDE4,A6NE82,A6NEC2,A6NED2,A6NEE1,A6NEL2,A6NEQ0,A6NEQ2,A6NES4,A6NF01,A6NFI3,A6NFR6,A6NFX1,A6NFY7,A6NGB7,A6NGC4,A6NGE4,A6NGG8,A6NGN9,A6NGR9,A6NGS2,A6NHG4,A6NHJ4,A6NHN6,A6NHQ4,A6NHT5,A6NI28,A6NI72,A6NI79,A6NIE6,A6NIH7,A6NIK2,A6NIY4,A6NJ46,A6NJ64,A6NJ78,A6NJG2,A6NJI1,A6NJT0,A6NJZ7,A6NK44,A6NK89,A6NKB5,A6NKD9,A6NKF7,A6NKG5,A6NKL6,A6NKN8,A6NKT7,A6NKU9,A6NL88,A6NLC5,A6NLJ0,A6NM28,A6NMD2,A6NMK8,A6NMT0,A6NMX2,A6NMY6,A6NMZ7,A6NN90,A6NNA2,A6NNA5,A6NNC1,A6NNE9,A6NNM3,A6NNY8,A6NNZ2,A6PVY3,A6QL63,A6QL64,A7E2F4,A7E2U8,A7E2V4,A7E2Y1,A7KAX9,A7MBM2,A7MCY6,A7MD48,A7XYQ1,A8CG34,A8K0Z3,A8K2U0,A8K5M9,A8K855,A8K8P3,A8K979,A8MPP1,A8MPS7,A8MQ03,A8MQ14,A8MQ27,A8MRT5,A8MT19,A8MT65,A8MT70,A8MTA8,A8MTJ3,A8MTJ6,A8MTL3,A8MTQ0,A8MTZ7,A8MU46,A8MU93,A8MUH7,A8MUU9,A8MV81,A8MVS1,A8MVS5,A8MVU1,A8MVX0,A8MW92,A8MWX3,A8MWY0,A8MX76,A8MXT2,A8MXV4,A8MYA2,A8MYP8,A8MYZ6,A8MZ97,A8MZF0,A8TX70,A9UHW6,A9YTQ3,B0FP48,B0I1T2,B0YJ81,B1AK53,B1ANS9,B2RBV5,B2RPK0,B2RTY4,B2RU33,B2RUZ4,B2RXF0,B2RXF5,B2RXH2,B3EWG6,B3KU38,B4DH59,B4DJY2,B4DS77,B7U540,B7Z1M9,B7Z6K7,B7ZAP0,B7ZBB8,B7ZC32,B9A064,C4AMC7,C9J069,C9J202,C9J798,C9J7I0,C9JG80,C9JI98,C9JLR9,C9JLW8,C9JQI7,C9JQL5,C9JRZ8,C9JTQ0,C9JVW0,D6RF30,D6RGH6,E5RHQ5,E5RIL1,E7ERA6,E7ETH6,E7EW31,E9PAV3,E9PB15,E9PGG2,E9PRG8,F5GYI3,F5H284,F5H4A9,F8WCM5,G2XKQ0,G3V0H7,G9CGD6,H0YL14,H3BPF8,H3BQB6,H3BQL2,H3BR10,H3BRN8,H3BSY2,H7BZ55,I3L273,I3L3R5,I6L899,K7EJ46,M0QZC1,M0R2J8,M5A8F1,O00116,O00124,O00141,O00148,O00151,O00154,O00155,O00159,O00160,O00161,O00165,O00167,O00168,O00170,O00180,O00182,O00189,O00192,O00193,O00194,O00203,O00204,O00212,O00213,O00214,O00217,O00220,O00221,O00222,O00231,O00232,O00233,O00238,O00255,O00264,O00267,O00268,O00273,O00287,O00291,O00294,O00299,O00300,O00303,O00305,O00308,O00311,O00321,O00327,O00330,O00337,O00338,O00358,O00370,O00391,O00400,O00401,O00408,O00409,O00410,O00411,O00418,O00421,O00422,O00423,O00425,O00429,O00442,O00443,O00444,O00453,O00458,O00459,O00462,O00463,O00469,O00470,O00471,O00472,O00478,O00479,O00481,O00483,O00487,O00488,O00499,O00501,O00505,O00506,O00507,O00515,O00519,O00522,O00533,O00534,O00541,O00548,O00555,O00559,O00560,O00562,O00566,O00567,O00570,O00571,O00574,O00585,O00590,O00591,O00592,O00622,O00623,O00625,O00635,O00712,O00716,O00743,O00744,O00746,O00750,O00754,O00757,O00762,O00763,O00764,O00767,O14490,O14492,O14493,O14495,O14497,O14503,O14508,O14511,O14513,O14514,O14519,O14520,O14522,O14523,O14524,O14525,O14526,O14529,O14530,O14531,O14543,O14544,O14545,O14548,O14558,O14559,O14561,O14562,O14576,O14578,O14579,O14594,O14595,O14598,O14602,O14604,O14607,O14613,O14617,O14618,O14626,O14628,O14638,O14639,O14640,O14641,O14645,O14646,O14647,O14649,O14654,O14662,O14668,O14672,O14681,O14682,O14683,O14686,O14713,O14715,O14727,O14730,O14732,O14733,O14734,O14744,O14745,O14753,O14756,O14757,O14771,O14772,O14773,O14775,O14776,O14777,O14782,O14786,O14787,O14795,O14796,O14798,O14802,O14807,O14810,O14813,O14818,O14827,O14828,O14829,O14830,O14832,O14836,O14841,O14843,O14862,O14863,O14867,O14874,O14879,O14880,O14893,O14896,O14901,O14907,O14908,O14910,O14917,O14920,O14924,O14929,O14936,O14939,O14948,O14949,O14958,O14964,O14965,O14966,O14967,O14974,O14975,O14976,O14978,O14979,O14980,O14981,O14983,O14986,O14994,O15014,O15015,O15016,O15018,O15020,O15021,O15027,O15031,O15033,O15034,O15037,O15040,O15042,O15047,O15049,O15050,O15054,O15055,O15056,O15061,O15062,O15063,O15066,O15067,O15068,O15069,O15075,O15078,O15079,O15083,O15084,O15085,O15090,O15091,O15111,O15116,O15117,O15118,O15119,O15120,O15121,O15126,O15127,O15131,O15143,O15144,O15145,O15146,O15151,O15155,O15156,O15160,O15162,O15164,O15165,O15169,O15172,O15173,O15178,O15182,O15194,O15195,O15197,O15198,O15204,O15209,O15211,O15212,O15213,O15218,O15226,O15228,O15229,O15231,O15232,O15234,O15239,O15240,O15243,O15244,O15245,O15247,O15254,O15258,O15260,O15264,O15265,O15269,O15270,O15273,O15287,O15294,O15296,O15297,O15304,O15305,O15318,O15321,O15327,O15344,O15347,O15350,O15353,O15354,O15355,O15357,O15360,O15370,O15371,O15372,O15374,O15375,O15379,O15389,O15391,O15392,O15393,O15394,O15399,O15403,O15405,O15409,O15427,O15431,O15432,O15438,O15439,O15440,O15446,O15455,O15460,O15479,O15481,O15484,O15492,O15498,O15503,O15504,O15511,O15514,O15516,O15523,O15525,O15530,O15533,O15534,O15541,O15551,O15552,O15553,O15554,O43143,O43147,O43148,O43149,O43150,O43151,O43157,O43159,O43164,O43166,O43167,O43169,O43175,O43182,O43189,O43194,O43236,O43237,O43240,O43242,O43246,O43247,O43248,O43251,O43252,O43255,O43264,O43272,O43281,O43290,O43291,O43292,O43293,O43294,O43296,O43298,O43299,O43300,O43301,O43303,O43304,O43306,O43307,O43309,O43312,O43313,O43314,O43315,O43318,O43324,O43325,O43345,O43347,O43353,O43361,O43365,O43374,O43379,O43390,O43395,O43396,O43414,O43422,O43423,O43426,O43432,O43435,O43439,O43447,O43448,O43463,O43464,O43474,O43482,O43488,O43490,O43491,O43493,O43497,O43502,O43504,O43505,O43513,O43516,O43520,O43521,O43524,O43525,O43526,O43541,O43543,O43548,O43555,O43556,O43559,O43566,O43567,O43570,O43572,O43581,O43583,O43592,O43593,O43597,O43598,O43602,O43603,O43609,O43610,O43613,O43615,O43623,O43633,O43638,O43639,O43660,O43663,O43665,O43670,O43674,O43676,O43678,O43679,O43680,O43681,O43683,O43684,O43687,O43688,O43699,O43707,O43708,O43709,O43711,O43716,O43719,O43736,O43741,O43745,O43752,O43759,O43760,O43761,O43765,O43768,O43772,O43781,O43790,O43791,O43808,O43815,O43818,O43819,O43822,O43823,O43829,O43837,O43847,O43852,O43861,O43865,O43868,O43889,O43895,O43896,O43900,O43903,O43909,O43913,O43914,O43916,O43920,O43924,O43929,O43930,O43933,O43934,O60216,O60218,O60220,O60229,O60231,O60232,O60234,O60237,O60238,O60239,O60240,O60241,O60244,O60248,O60256,O60260,O60262,O60264,O60266,O60268,O60269,O60271,O60279,O60281,O60282,O60284,O60287,O60290,O60291,O60292,O60293,O60294,O60296,O60299,O60303,O60304,O60306,O60307,O60308,O60312,O60313,O60315,O60318,O60320,O60331,O60333,O60336,O60337,O60341,O60346,O60347,O60353,O60361,O60381,O60391,O60393,O60427,O60437,O60443,O60447,O60449,O60462,O60469,O60476,O60478,O60481,O60486,O60487,O60493,O60496,O60499,O60500,O60503,O60504,O60506,O60507,O60508,O60516,O60518,O60522,O60524,O60547,O60548,O60551,O60563,O60565,O60566,O60568,O60573,O60613,O60637,O60641,O60645,O60656,O60658,O60662,O60663,O60664,O60669,O60671,O60673,O60674,O60675,O60678,O60682,O60683,O60684,O60701,O60704,O60706,O60711,O60716,O60729,O60732,O60733,O60739,O60741,O60749,O60759,O60762,O60763,O60765,O60779,O60784,O60812,O60814,O60825,O60826,O60829,O60831,O60832,O60841,O60858,O60861,O60869,O60870,O60879,O60883,O60884,O60885,O60890,O60902,O60907,O60921,O60925,O60927,O60928,O60930,O60934,O60936,O60939,O60941,O60942,O75022,O75023,O75027,O75030,O75037,O75038,O75044,O75051,O75054,O75056,O75061,O75064,O75071,O75074,O75077,O75081,O75083,O75084,O75094,O75095,O75096,O75110,O75113,O75116,O75121,O75122,O75123,O75127,O75128,O75129,O75131,O75132,O75140,O75143,O75145,O75146,O75147,O75150,O75151,O75152,O75153,O75154,O75155,O75157,O75159,O75161,O75164,O75165,O75167,O75170,O75175,O75179,O75182,O75190,O75191,O75192,O75197,O75204,O75208,O75223,O75251,O75264,O75290,O75298,O75309,O75312,O75319,O75324,O75330,O75334,O75343,O75347,O75348,O75351,O75355,O75356,O75362,O75363,O75364,O75366,O75367,O75368,O75369,O75376,O75379,O75381,O75382,O75385,O75386,O75387,O75390,O75391,O75396,O75398,O75400,O75410,O75417,O75419,O75425,O75427,O75431,O75436,O75439,O75444,O75445,O75446,O75448,O75449,O75459,O75460,O75461,O75462,O75467,O75473,O75475,O75477,O75478,O75486,O75487,O75489,O75494,O75496,O75508,O75509,O75521,O75525,O75526,O75528,O75529,O75530,O75531,O75533,O75534,O75541,O75553,O75558,O75563,O75564,O75569,O75575,O75581,O75582,O75586,O75592,O75593,O75596,O75602,O75604,O75607,O75616,O75626,O75628,O75631,O75638,O75643,O75663,O75665,O75676,O75683,O75688,O75689,O75691,O75694,O75695,O75712,O75716,O75717,O75718,O75746,O75747,O75751,O75762,O75764,O75781,O75787,O75791,O75792,O75794,O75800,O75808,O75815,O75817,O75820,O75822,O75828,O75829,O75832,O75843,O75844,O75845,O75871,O75874,O75881,O75884,O75886,O75888,O75891,O75896,O75897,O75899,O75909,O75911,O75915,O75920,O75923,O75925,O75928,O75934,O75935,O75936,O75937,O75940,O75943,O75947,O75953,O75955,O75956,O75962,O75964,O75969,O75970,O75971,O75976,O75995,O76003,O76013,O76015,O76021,O76024,O76027,O76038,O76039,O76041,O76050,O76054,O76061,O76064,O76070,O76071,O76074,O76076,O76080,O76081,O76082,O76083,O76087,O76094,O94759,O94761,O94762,O94768,O94769,O94772,O94778,O94782,O94805,O94806,O94808,O94811,O94812,O94819,O94827,O94829,O94830,O94832,O94842,O94844,O94850,O94851,O94854,O94855,O94856,O94864,O94874,O94875,O94876,O94880,O94887,O94888,O94889,O94892,O94898,O94900,O94901,O94903,O94905,O94906,O94907,O94910,O94911,O94913,O94915,O94916,O94919,O94921,O94923,O94925,O94927,O94929,O94933,O94941,O94953,O94955,O94956,O94964,O94966,O94967,O94972,O94973,O94979,O94983,O94985,O94986,O94988,O94989,O94991,O94992,O94993,O95049,O95050,O95067,O95069,O95070,O95071,O95072,O95076,O95081,O95096,O95104,O95125,O95136,O95139,O95140,O95150,O95153,O95154,O95155,O95159,O95163,O95164,O95167,O95168,O95171,O95182,O95183,O95185,O95196,O95197,O95199,O95201,O95202,O95206,O95210,O95218,O95229,O95231,O95232,O95235,O95236,O95238,O95239,O95248,O95249,O95251,O95255,O95259,O95260,O95263,O95267,O95274,O95279,O95292,O95295,O95297,O95298,O95299,O95319,O95336,O95340,O95343,O95347,O95352,O95359,O95365,O95372,O95373,O95376,O95379,O95382,O95391,O95394,O95396,O95398,O95400,O95402,O95405,O95409,O95415,O95425,O95429,O95433,O95436,O95447,O95452,O95453,O95456,O95461,O95466,O95467,O95470,O95471,O95475,O95476,O95477,O95479,O95484,O95486,O95487,O95490,O95500,O95502,O95503,O95544,O95551,O95562,O95568,O95571,O95573,O95600,O95613,O95622,O95625,O95626,O95628,O95630,O95633,O95639,O95644,O95665,O95671,O95672,O95674,O95678,O95684,O95685,O95696,O95704,O95707,O95714,O95716,O95718,O95721,O95741,O95747,O95751,O95754,O95755,O95757,O95759,O95760,O95772,O95777,O95780,O95782,O95785,O95786,O95789,O95793,O95801,O95807,O95810,O95816,O95817,O95819,O95822,O95825,O95831,O95832,O95833,O95837,O95848,O95857,O95859,O95861,O95863,O95864,O95866,O95870,O95872,O95900,O95905,O95907,O95922,O95926,O95931,O95935,O95936,O95948,O95954,O95976,O95977,O95980,O95983,O95985,O95989,O95990,O95994,O95995,O95996,O95997,O95999,O96000,O96001,O96005,O96006,O96007,O96008,O96013,O96017,O96018,O96019,O96020,O96028,P00167,P00325,P00326,P00338,P00352,P00367,P00374,P00387,P00390,P00403,P00439,P00441,P00450,P00451,P00480,P00488,P00491,P00492,P00505,P00519,P00533,P00558,P00568,P00734,P00736,P00738,P00740,P00742,P00746,P00747,P00748,P00751,P00915,P00966,P00973,P00995,P01008,P01009,P01011,P01023,P01024,P01033,P01034,P01040,P01042,P01100,P01106,P01111,P01112,P01116,P01127,P01130,P01189,P01210,P01258,P01266,P01275,P01303,P01344,P01562,P01583,P01584,P01591,P01602,P01730,P01732,P01833,P01834,P01857,P01859,P01861,P01871,P01876,P01889,P01891,P01892,P01893,P01903,P01911,P02008,P02100,P02144,P02452,P02461,P02489,P02511,P02533,P02538,P02545,P02549,P02585,P02647,P02649,P02652,P02655,P02656,P02675,P02689,P02724,P02743,P02748,P02749,P02751,P02753,P02760,P02763,P02765,P02766,P02768,P02771,P02774,P02775,P02786,P02787,P02788,P02790,P02792,P02794,P02795,P02808,P03372,P03928,P03956,P03989,P04004,P04035,P04053,P04075,P04080,P04083,P04085,P04114,P04150,P04155,P04156,P04179,P04181,P04183,P04196,P04198,P04216,P04222,P04229,P04233,P04234,P04259,P04264,P04279,P04350,P04406,P04424,P04439,P04626,P04632,P04637,P04731,P04732,P04733,P04792,P04798,P04818,P04839,P04843,P04844,P04899,P04908,P04920,P04921,P05023,P05026,P05060,P05062,P05067,P05089,P05090,P05091,P05106,P05107,P05109,P05120,P05121,P05129,P05141,P05160,P05161,P05162,P05164,P05165,P05166,P05177,P05181,P05186,P05187,P05198,P05204,P05230,P05231,P05305,P05362,P05386,P05387,P05388,P05408,P05413,P05423,P05452,P05455,P05496,P05534,P05546,P05549,P05556,P05771,P05787,P05814,P05937,P05976,P05997,P06127,P06132,P06213,P06239,P06307,P06400,P06454,P06493,P06576,P06702,P06703,P06727,P06729,P06730,P06731,P06732,P06733,P06734,P06737,P06744,P06746,P06748,P06753,P06756,P06881,P07099,P07101,P07148,P07195,P07196,P07197,P07199,P07203,P07204,P07205,P07225,P07237,P07305,P07311,P07315,P07327,P07332,P07333,P07358,P07359,P07360,P07384,P07437,P07451,P07476,P07492,P07550,P07585,P07602,P07737,P07738,P07741,P07766,P07814,P07858,P07864,P07900,P07902,P07910,P07911,P07942,P07948,P07949,P07951,P07988,P07992,P07996,P07998,P08034,P08047,P08048,P08069,P08100,P08123,P08133,P08134,P08138,P08151,P08172,P08173,P08174,P08183,P08185,P08195,P08235,P08237,P08238,P08240,P08243,P08246,P08253,P08263,P08311,P08319,P08397,P08476,P08493,P08514,P08559,P08567,P08572,P08574,P08575,P08579,P08581,P08582,P08588,P08590,P08603,P08621,P08631,P08648,P08651,P08684,P08697,P08708,P08709,P08727,P08729,P08754,P08758,P08779,P08833,P08865,P08887,P08908,P08910,P08912,P08913,P08922,P08962,P08F94,P09001,P09012,P09016,P09017,P09038,P09067,P09086,P09210,P09234,P09238,P09327,P09382,P09417,P09429,P09467,P09471,P09488,P09493,P09496,P09497,P09525,P09543,P09564,P09565,P09601,P09603,P09619,P09622,P09630,P09661,P09669,P09693,P09758,P09769,P09871,P09874,P09884,P09912,P09913,P09914,P09923,P09936,P09958,P09960,P09972,P0C024,P0C091,P0C0L4,P0C0L5,P0C0S5,P0C0S8,P0C1Z6,P0C264,P0C2L3,P0C5K6,P0C623,P0C671,P0C6C1,P0C7M4,P0C7M8,P0C7P1,P0C7P4,P0C7T5,P0C7T7,P0C7T8,P0C7U0,P0C7U9,P0C7V6,P0C7V9,P0C7W0,P0C842,P0C851,P0C860,P0C869,P0C870,P0C881,P0CAP2,P0CF74,P0CG04,P0CG08,P0CG12,P0CG20,P0CG23,P0CG24,P0CG29,P0CG30,P0CG31,P0CG35,P0CG38,P0CG39,P0CG40,P0CG41,P0CG47,P0CG48,P0CJ78,P0CJ92,P0CK96,P0CK97,P0CL80,P0CL81,P0CL82,P0CL83,P0CW01,P0DI81,P0DI82,P0DI83,P0DJ93,P0DJD0,P0DJD1,P0DJD3,P0DJD4,P0DJI8,P0DJI9,P0DJJ0,P0DKX0,P0DM35,P0DME0,P0DMM9,P0DMN0,P0DMP2,P0DMS8,P0DMU7,P0DMU8,P0DMU9,P0DMV0,P0DMV1,P0DMV2,P0DMV8,P0DN24,P0DN26,P0DN37,P0DN79,P0DN80,P0DOX5,P0DOX7,P0DOX8,P0DOY2,P0DOY3,P0DP24,P0DP25,P0DP58,P0DP72,P0DP91,P0DPA3,P0DPB3,P0DPB5,P0DPB6,P0DPD7,P0DPD8,P0DPE8,P0DPF2,P0DPF3,P0DPH7,P0DPH8,P0DPI2,P10070,P10071,P10072,P10073,P10074,P10109,P10114,P10124,P10155,P10242,P10243,P10244,P10275,P10276,P10301,P10314,P10316,P10319,P10321,P10398,P10412,P10415,P10451,P10515,P10523,P10586,P10588,P10589,P10599,P10619,P10620,P10632,P10636,P10643,P10644,P10645,P10696,P10721,P10745,P10746,P10747,P10768,P10827,P10912,P10914,P10916,P10966,P11021,P11047,P11055,P11086,P11137,P11142,P11161,P11168,P11169,P11171,P11177,P11182,P11215,P11216,P11217,P11229,P11233,P11234,P11274,P11277,P11279,P11308,P11309,P11310,P11362,P11388,P11413,P11441,P11473,P11474,P11488,P11509,P11532,P11586,P11684,P11686,P11712,P11717,P11766,P11802,P11831,P11836,P11908,P11912,P12004,P12035,P12036,P12074,P12081,P12107,P12109,P12110,P12111,P12235,P12236,P12259,P12268,P12270,P12271,P12272,P12277,P12314,P12318,P12429,P12524,P12532,P12643,P12644,P12645,P12694,P12724,P12755,P12757,P12814,P12821,P12830,P12872,P12882,P12883,P12931,P12955,P12980,P13010,P13051,P13056,P13073,P13164,P13196,P13224,P13378,P13489,P13498,P13521,P13533,P13535,P13569,P13584,P13591,P13611,P13612,P13631,P13637,P13639,P13640,P13645,P13646,P13647,P13667,P13674,P13682,P13686,P13688,P13693,P13716,P13726,P13746,P13747,P13760,P13761,P13762,P13765,P13796,P13797,P13804,P13805,P13861,P13866,P13928,P13929,P13984,P13994,P13995,P14136,P14138,P14174,P14207,P14209,P14314,P14316,P14324,P14415,P14416,P14543,P14550,P14618,P14621,P14625,P14635,P14649,P14651,P14652,P14672,P14735,P14778,P14780,P14784,P14854,P14859,P14867,P14868,P14921,P14923,P15018,P15036,P15056,P15090,P15104,P15144,P15151,P15153,P15170,P15172,P15259,P15260,P15291,P15311,P15313,P15336,P15374,P15391,P15407,P15408,P15428,P15498,P15509,P15529,P15531,P15559,P15586,P15622,P15735,P15814,P15822,P15848,P15863,P15882,P15884,P15907,P15923,P15924,P15927,P15941,P15954,P15976,P16050,P16070,P16083,P16104,P16109,P16112,P16118,P16144,P16150,P16152,P16157,P16188,P16189,P16190,P16219,P16220,P16284,P16333,P16383,P16389,P16401,P16402,P16403,P16415,P16435,P16452,P16455,P16471,P16473,P16519,P16581,P16591,P16662,P16870,P16871,P16885,P16930,P16949,P16989,P17010,P17014,P17017,P17020,P17022,P17023,P17025,P17026,P17027,P17028,P17029,P17031,P17032,P17035,P17036,P17038,P17040,P17041,P17096,P17097,P17098,P17152,P17174,P17181,P17252,P17301,P17302,P17342,P17480,P17481,P17483,P17509,P17516,P17535,P17540,P17542,P17544,P17568,P17600,P17655,P17658,P17661,P17676,P17677,P17706,P17707,P17735,P17752,P17787,P17812,P17813,P17844,P17858,P17861,P17927,P17931,P17936,P17947,P17948,P17987,P18031,P18065,P18074,P18077,P18084,P18085,P18089,P18124,P18146,P18206,P18283,P18433,P18440,P18462,P18463,P18464,P18465,P18505,P18510,P18564,P18583,P18615,P18621,P18627,P18669,P18754,P18827,P18846,P18847,P18848,P18850,P18858,P18887,P19012,P19021,P19022,P19086,P19087,P19105,P19113,P19174,P19237,P19320,P19338,P19367,P19387,P19388,P19404,P19419,P19438,P19447,P19474,P19525,P19532,P19544,P19622,P19623,P19634,P19652,P19784,P19793,P19801,P19823,P19827,P19838,P19878,P19957,P19971,P20020,P20023,P20039,P20042,P20073,P20132,P20138,P20231,P20248,P20264,P20265,P20273,P20290,P20309,P20333,P20336,P20337,P20338,P20339,P20340,P20366,P20393,P20396,P20472,P20585,P20591,P20594,P20618,P20648,P20671,P20674,P20700,P20701,P20711,P20719,P20749,P20794,P20810,P20813,P20827,P20839,P20849,P20853,P20908,P20929,P20930,P20941,P20962,P20963,P21108,P21127,P21128,P21246,P21266,P21281,P21283,P21291,P21333,P21359,P21399,P21439,P21452,P21453,P21462,P21549,P21554,P21579,P21580,P21583,P21675,P21695,P21709,P21728,P21730,P21731,P21757,P21796,P21802,P21810,P21815,P21817,P21854,P21912,P21917,P21918,P21926,P21964,P22001,P22033,P22059,P22061,P22079,P22090,P22102,P22105,P22223,P22234,P22307,P22310,P22314,P22362,P22392,P22415,P22455,P22459,P22460,P22466,P22492,P22528,P22531,P22532,P22570,P22607,P22612,P22626,P22670,P22674,P22676,P22680,P22681,P22692,P22694,P22695,P22732,P22735,P22748,P22760,P22792,P22794,P22897,P23025,P23109,P23142,P23229,P23246,P23258,P23276,P23284,P23297,P23327,P23352,P23381,P23396,P23434,P23443,P23458,P23467,P23468,P23469,P23471,P23497,P23508,P23511,P23515,P23526,P23527,P23528,P23588,P23634,P23743,P23760,P23763,P23769,P23771,P23919,P23921,P24001,P24043,P24278,P24298,P24385,P24386,P24394,P24468,P24534,P24539,P24588,P24593,P24723,P24752,P24821,P24844,P24863,P24864,P24928,P24941,P25021,P25025,P25054,P25089,P25090,P25098,P25101,P25103,P25106,P25116,P25205,P25208,P25325,P25391,P25398,P25440,P25445,P25490,P25685,P25686,P25713,P25786,P25787,P25788,P25789,P25791,P25929,P25940,P25963,P26006,P26010,P26012,P26038,P26045,P26232,P26358,P26367,P26368,P26373,P26374,P26378,P26439,P26440,P26447,P26583,P26599,P26639,P26640,P26651,P26678,P26842,P26951,P26998,P27037,P27105,P27144,P27216,P27338,P27348,P27352,P27361,P27448,P27482,P27540,P27544,P27635,P27694,P27695,P27707,P27708,P27815,P27816,P27824,P27986,P27987,P28062,P28065,P28066,P28068,P28070,P28072,P28074,P28161,P28222,P28288,P28290,P28300,P28324,P28329,P28330,P28331,P28332,P28340,P28347,P28356,P28358,P28360,P28370,P28472,P28482,P28562,P28698,P28702,P28715,P28749,P28799,P28827,P28838,P28906,P28908,P29033,P29034,P29074,P29083,P29084,P29120,P29144,P29218,P29274,P29317,P29320,P29322,P29323,P29350,P29371,P29372,P29373,P29374,P29375,P29400,P29401,P29466,P29475,P29508,P29558,P29590,P29597,P29692,P29728,P29762,P29803,P29966,P29992,P30038,P30039,P30040,P30041,P30044,P30046,P30048,P30050,P30084,P30085,P30086,P3

In [85]:
prot_info = prepare_prot_info(test_mapping_path, train_mapping_path, test_st, train_st)
prepare_splits(prot_info, label='ST')
prot_info.to_json('../data/deepmvp/deepmvp_info_ST.json', indent=4)

Label: test
Updated IDs: 1
Duplicated IDs: Empty DataFrame
Columns: [aa, pos, x, y, Entry, Reviewed, Entry Name, Sequence]
Index: []
Missing Sequences: 1                                                         aa  \
protein
Q9Y6X9   [T, S, S, T, S, T, S, S, S, T, T, S, S, S, S, ...

                                                       pos  \
protein
Q9Y6X9   [91, 513, 514, 599, 602, 603, 615, 627, 631, 6...

                                                         x  \
protein
Q9Y6X9   [GFMLCFLDDGAGMDPSDAASVIQFGKSAKRTPESTQIGQYGNGLK...

                                                         y Entry Reviewed  \
protein
Q9Y6X9   [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...   NaN      NaN

        Entry Name Sequence
protein
Q9Y6X9         NaN      NaN
Mismatched sequences: 28

Label: train
Updated IDs: 79
Duplicated IDs:             aa        pos                                                  x  \
P01562  [S, S]  [50, 176]  [CSLGCDLPETHSLDNRRTLMLLAQMSRISPSSCLMDRHDFGFPQE...
P01562  [S, S]  [50, 176]  [CSLGCDLPETHSLDNRRTLMLLAQMSRISPSSCLMDRHDFGFPQE...
Q13065     [T]       [40]  [YWPRPRRYVQPPEMIGPMRPEQFSDEVEPATPEEGEPATQRQDPA...
Q13065     [T]       [40]  [YWPRPRRYVQPPEMIGPMRPEQFSDEVEPATPEEGEPATQRQDPA...
Q13068  [T, S]  [40, 115]  [YWPRPRRYVQPPEMIGPMRPEQFSDEVEPATPEEGEPATQRQDPA...
Q13068  [T, S]  [40, 115]  [YWPRPRRYVQPPEMIGPMRPEQFSDEVEPATPEEGEPATQRQDPA...
Q6ZMK1     [S]      [137]  [QATCPNCRCEISKSLCCRNLAVEKAVSELPSECGFCLRQFPRSLL...
Q6ZMK1     [S]      [137]  [QATCPNCRCEISKSLCCRNLAVEKAVSELPSECGFCLRQFPRSLL...

             y       Entry   Entry Name  \
P01562  [1, 1]  A0A087WWS6  IFNAD_HUMAN
P01562  [1, 1]      P0DY56  IFNA1_HUMAN
Q13065     [1]      P0DSO3  GAGE4_HUMAN
Q13065     [1]      P0DTW1  GAGE1_HUMAN
Q13068  [1, 1]      P0DSO3  GAGE4_HUMAN
Q13068  [1, 1]      P0DTW1  GAGE1_HUMAN
Q6ZMK1     [1]      P0DTL5  TM276_HUMAN
Q6ZMK1     [1]      P0DTL6  ZTRF1_HUMAN

                                                 Sequence
P01562  MMASPFALLMALVVLSCKSSCSLGCDLPETHSLDNRRTLMLLAQMS...
P01562  MASPFALLMVLVVLSCKSSCSLGCDLPETHSLDNRRTLMLLAQMSR...
Q13065  MSWRGRSTYYWPRPRRYVQPPEMIGPMRPEQFSDEVEPATPEEGEP...
Q13065  MSWRGRSTYYWPRPRRYVQPPEMIGPMRPEQFSDEVEPATPEEGEP...
Q13068  MSWRGRSTYYWPRPRRYVQPPEMIGPMRPEQFSDEVEPATPEEGEP...
Q13068  MSWRGRSTYYWPRPRRYVQPPEMIGPMRPEQFSDEVEPATPEEGEP...
Q6ZMK1  MAPKPGAEWSTALSHLVLGVVSLHAAVSTAEASRGAAAGFLLQVLA...
Q6ZMK1  MSGAEEAGGGGPAAGPAGSVPAGVGVGVGAGPGAAAGQAAAAALGE...

C:\Users\Samo\AppData\Local\Temp\ipykernel_28428\2953211020.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_info.loc[:, 'original_label'] = label

Missing Sequences: 14                                                            aa  \
A0A0B4J2F2  [S, S, S, S, T, S, S, S, S, S, S, S, S, S, S, ...
A8MVS1                                                    [S]
O60361                                        [T, S, S, S, S]
P0C842                                              [T, T, T]
P0DN24                                           [S, S, S, S]
P0DN79                                     [S, S, S, S, S, S]
P0DPE8                                                    [T]
Q12799                                                    [S]
Q5SRD0      [S, S, S, S, S, S, S, S, S, S, S, S, S, S, S, ...
Q8N7I0                                                    [S]
Q8NAS9                                                    [S]
Q8NG57                                                 [S, S]
Q9BZD3                                     [S, S, S, T, S, S]
Q9Y6Z5                                                    [S]

                                                          pos  \
A0A0B4J2F2  [186, 435, 437, 438, 473, 516, 534, 575, 626, ...
A8MVS1                                                  [103]
O60361                                [79, 84, 105, 107, 110]
P0C842                                        [108, 113, 114]
P0DN24                                       [39, 42, 60, 78]
P0DN79                              [27, 32, 61, 63, 73, 199]
P0DPE8                                                  [138]
Q12799                                                  [236]
Q5SRD0      [20, 21, 42, 54, 81, 86, 90, 99, 109, 111, 136...
Q8N7I0                                                  [128]
Q8NAS9                                                   [29]
Q8NG57                                             [121, 125]
Q9BZD3                         [144, 178, 179, 184, 364, 365]
Q9Y6Z5                                                  [239]

                                                            x  \
A0A0B4J2F2  [LLDGNMDIKLADFGFGNFYKSGEPLSTWCGSPPYAAPEVFEGKEY...
A8MVS1      [LQDQNPDRESALKKKHMISMHPIIRKDASTSMTMSKTLILEDPFE...
O60361      [LVKYMNSGPVVAMVWEGLNVVKTGRVMLGETNPADSKPGTIRGDF...
P0C842      [AGVPAKEVAGSRTGVFIGIMNQDYEFMSRRTPRMQTTVMPLDLQX...
P0DN24      [GQEPLDMFFWVNEISGEITYPPQKADAPAVSPESPQKKPPFQPRS...
P0DN79      [XXXXMPSETPQAEVGPTGCPHRSGPHSAKGSLEKGSPEDKEAKEP...
P0DPE8      [SISNRAVLQPCQAHLGAKGGSSGPQTATPETPXXXXXXXXXXXXX...
Q12799      [TPGAERRGVSEDGKIMHPSSRSPQNSGGRKSPVQASQATTLQEQT...
Q5SRD0      [XXXXXXXXXXXMRGKRRPQTRAARRLAAQESSEAEDMSVPRGPIA...
Q8N7I0      [RWSLALSPRQWCDLGSLQPPSPRFKGFSCLSLPSSWDYRRAPSPA...
Q8NAS9      [XXMPEPPTPSVGSCAARASRMSAAPCSRAPSPIDHPRAEECGRAA...
Q8NG57      [EESASRQRFGEALQEREKAWGFPENATAPRSPSHSPEHRRTARRT...
Q9BZD3      [GCSSVDNIKSSQTSQNQGLGRPTLEGDEETSEVEYTVNKGPASSN...
Q9Y6Z5      [APRARCSSCPRIAPGLLRVSSRVIPFRWVTSKPTFSSCFLPRRTR...

                                                            y       Entry  \
A0A0B4J2F2  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, ...  A0A0B4J2F2
A8MVS1                                                    [1]      A8MVS1
O60361                                        [1, 1, 1, 1, 1]      O60361
P0C842                                              [1, 1, 1]      P0C842
P0DN24                                           [1, 1, 1, 1]      P0DN24
P0DN79                                     [1, 1, 1, 1, 1, 1]      P0DN79
P0DPE8                                                    [1]      P0DPE8
Q12799                                                    [1]      Q12799
Q5SRD0      [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, ...      Q5SRD0
Q8N7I0                                                    [1]      Q8N7I0
Q8NAS9                                                    [1]      Q8NAS9
Q8NG57                                                 [1, 1]      Q8NG57
Q9BZD3                                     [1, 1, 1, 1, 1, 1]      Q9BZD3
Q9Y6Z5                                                    [1]         NaN

             Entry Name Sequence
A0A0B4J2F2  SIK1B_HUMAN      NaN
A8MVS1      Z705F_HUMAN      NaN
O60361       NDK8_HUMAN      NaN
P0C842      CJ052_HUMAN      NaN
P0DN24      CC086_HUMAN      NaN
P0DN79       CBSL_HUMAN      NaN
P0DPE8      SM34B_HUMAN      NaN
Q12799      TCP10_HUMAN      NaN
Q5SRD0      WAC2D_HUMAN      NaN
Q8N7I0      GVQW1_HUMAN      NaN
Q8NAS9      CE017_HUMAN      NaN
Q8NG57      ELOA3_HUMAN      NaN
Q9BZD3      GCOM2_HUMAN      NaN
Q9Y6Z5              NaN      NaN
Mismatched sequences: 253

C:\Users\Samo\AppData\Local\Temp\ipykernel_28428\2953211020.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_info.loc[:, 'original_label'] = label

In [86]:
prot_info.index[-1]

11324