In [1]:
import pandas as pd
import json

In [2]:
model = 'finetuning_STY_3_perturb2_dbptm'
fold = 0
path = f'../model/new_logs/{model}/fold_{fold}/test_preds_fold_{fold}.json'

preds = pd.read_json(path)
preds

,logits,labels,sequence_indices,df_index
0,"[-0.4687289596, -0.2807944119, -0.615130662900...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[7, 8, 10, 11, 13, 30, 31, 35, 46, 47, 50, 51,...",0
1,"[-0.1923001856, 0.4440064132, 0.0590357035, 0....","[0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, ...","[2, 7, 12, 13, 17, 19, 29, 35, 43, 49, 51, 62,...",1
2,"[-1.0600683689000001, -1.1709635258, -0.639483...","[0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...","[1, 6, 9, 13, 16, 20, 22, 26, 29, 30, 31, 33, ...",2
3,"[-2.9090206623, -2.9581665993, -3.4678504467, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[5, 6, 15, 17, 20, 21, 24, 26, 30, 47, 49, 59,...",3
4,"[-1.5819313526, -1.7183920145, -2.2351703644, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[12, 13, 18, 20, 21, 24, 28, 29, 49, 53, 56, 5...",4
...,...,...,...,...
1701,"[-1.7532222271, -1.9336031675, -2.0672709942, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[7, 8, 9, 10, 16, 27, 28, 34, 42, 46, 49, 50, ...",1701
1702,"[-2.7042791843, -2.3737132549, -2.654166936900...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[7, 11, 14, 19, 25, 31, 34, 35, 38, 42, 44, 47...",1702
1703,"[-3.0525510311, -3.134591341, -3.1323049068, -...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[5, 7, 9, 13, 14, 20, 28, 29, 30, 31, 32, 33, ...",1703
1704,"[-3.3001701832, -2.6730852127, -1.9795051813, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[26, 28, 35, 42, 48, 55, 68, 77, 84, 85, 89, 9...",1704
1705,"[1.2952928543, 2.0070812702, 2.2287652493, 1.2...","[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[1, 5, 7, 10, 18, 32, 33, 41, 42, 43, 45, 46, ...",1705

In [3]:
splits_path = '../data/dbptm/splits_STY.json'
with open(splits_path, 'r')  as f:
    splits = json.load(f)

In [4]:
prot_info_path = '../data/dbptm/dbptm_info.json'
prot_info = pd.read_json(prot_info_path)

In [5]:
prots = prot_info.iloc[splits[fold]['test']]

In [6]:
prots

,id,sites,sequence
0,A0A023PXF8,"[113, 119]",MRIQKQQYTISSNSRINLLGILVLNVVCGKSSIFFSHPQRLGKLGG...
3,A0A023PZG4,"[14, 18]",MHTICLRSPIDESSPLPYKSIRQPLENAHSCQALCSLMAVLCASAA...
50,A0A096LP01,"[14, 17, 21, 23, 27, 30, 31, 32, 34, 52, 55]",MYRNEFTAWYRRMSVVYGIGTWSVLGSLLYYSRTMAKSSVDQKDGS...
175,A0A1B0GTH6,"[170, 172, 183, 401, 662, 72]",MVPLAYYGQHFVPLDYFYQLSSANTLTHQHTGEKLNQFNNQPMAKV...
188,A0A1B0GV85,"[290, 291, 293, 296, 297, 299, 300]",MRMQAALVGWACTTLCLASCSSAFSHGASTVACDDMQPKHIQAQPQ...
...,...,...,...
60055,Q9ZUH0,[51],MAMKKKISTSSIMPDWSQLPEELLHIISTHLEDHYFDAVHARSVCR...
60062,Q9ZUN3,"[575, 577]",MRRCKNNTDKFSVITMRLLTLLLICTFFFFFSFAYSAESDNETDSV...
60070,Q9ZUS8,"[228, 252, 253, 255]",MDLHESESRTHVLSTDGDDGYIDMEVNLSSSSSSSTSSSSFFSFPV...
60162,T1NXB5,"[222, 223, 226, 228]",MRLRLLALAAAVLLGPAPEVCGALNVTVSPGPVVDYLEGENATLLC...
60163,U4PLN7,"[170, 2]",MSRDVSLSPKSGDIRFNGTEPPVKVEVVDEEQSSLNNQLGFSTTLS...

In [7]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

preds['probs'] = preds['logits'].apply(lambda x: sigmoid(np.asarray(x)))
preds[['probs', 'sequence_indices']]

,probs,sequence_indices
0,"[0.3849171259113849, 0.4302590261695979, 0.350...","[7, 8, 10, 11, 13, 30, 31, 35, 46, 47, 50, 51,..."
1,"[0.4520725565074163, 0.6092132636565196, 0.514...","[2, 7, 12, 13, 17, 19, 29, 35, 43, 49, 51, 62,..."
2,"[0.2572963895284866, 0.23668086661603296, 0.34...","[1, 6, 9, 13, 16, 20, 22, 26, 29, 30, 31, 33, ..."
3,"[0.05170943677158174, 0.04935195149422556, 0.0...","[5, 6, 15, 17, 20, 21, 24, 26, 30, 47, 49, 59,..."
4,"[0.17052212928289434, 0.15207839830319062, 0.0...","[12, 13, 18, 20, 21, 24, 28, 29, 49, 53, 56, 5..."
...,...,...
1701,"[0.14764124175901985, 0.12635230006365028, 0.1...","[7, 8, 9, 10, 16, 27, 28, 34, 42, 46, 49, 50, ..."
1702,"[0.0627213228963844, 0.08519928087373167, 0.06...","[7, 11, 14, 19, 25, 31, 34, 35, 38, 42, 44, 47..."
1703,"[0.0451074658777046, 0.04170273388698797, 0.04...","[5, 7, 9, 13, 14, 20, 28, 29, 30, 31, 32, 33, ..."
1704,"[0.035565351449662545, 0.06458034120899207, 0....","[26, 28, 35, 42, 48, 55, 68, 77, 84, 85, 89, 9..."
1705,"[0.7850417122744976, 0.8815385633915113, 0.902...","[1, 5, 7, 10, 18, 32, 33, 41, 42, 43, 45, 46, ..."

In [8]:
np.sum([x in {'S', 'T', 'Y'} for x in prot_info.iloc[0]['sequence']])

np.int64(37)

In [9]:
preds[['orig_index','sequence']] = prots['sequence'].reset_index()

In [10]:
preds[['labels', 'sequence_indices', 'probs', 'sequence']]

,labels,sequence_indices,probs,sequence
0,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[7, 8, 10, 11, 13, 30, 31, 35, 46, 47, 50, 51,...","[0.3849171259113849, 0.4302590261695979, 0.350...",MRIQKQQYTISSNSRINLLGILVLNVVCGKSSIFFSHPQRLGKLGG...
1,"[0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, ...","[2, 7, 12, 13, 17, 19, 29, 35, 43, 49, 51, 62,...","[0.4520725565074163, 0.6092132636565196, 0.514...",MHTICLRSPIDESSPLPYKSIRQPLENAHSCQALCSLMAVLCASAA...
2,"[0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...","[1, 6, 9, 13, 16, 20, 22, 26, 29, 30, 31, 33, ...","[0.2572963895284866, 0.23668086661603296, 0.34...",MYRNEFTAWYRRMSVVYGIGTWSVLGSLLYYSRTMAKSSVDQKDGS...
3,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[5, 6, 15, 17, 20, 21, 24, 26, 30, 47, 49, 59,...","[0.05170943677158174, 0.04935195149422556, 0.0...",MVPLAYYGQHFVPLDYFYQLSSANTLTHQHTGEKLNQFNNQPMAKV...
4,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[12, 13, 18, 20, 21, 24, 28, 29, 49, 53, 56, 5...","[0.17052212928289434, 0.15207839830319062, 0.0...",MRMQAALVGWACTTLCLASCSSAFSHGASTVACDDMQPKHIQAQPQ...
...,...,...,...,...
1701,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[7, 8, 9, 10, 16, 27, 28, 34, 42, 46, 49, 50, ...","[0.14764124175901985, 0.12635230006365028, 0.1...",MAMKKKISTSSIMPDWSQLPEELLHIISTHLEDHYFDAVHARSVCR...
1702,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[7, 11, 14, 19, 25, 31, 34, 35, 38, 42, 44, 47...","[0.0627213228963844, 0.08519928087373167, 0.06...",MRRCKNNTDKFSVITMRLLTLLLICTFFFFFSFAYSAESDNETDSV...
1703,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[5, 7, 9, 13, 14, 20, 28, 29, 30, 31, 32, 33, ...","[0.0451074658777046, 0.04170273388698797, 0.04...",MDLHESESRTHVLSTDGDDGYIDMEVNLSSSSSSSTSSSSFFSFPV...
1704,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[26, 28, 35, 42, 48, 55, 68, 77, 84, 85, 89, 9...","[0.035565351449662545, 0.06458034120899207, 0....",MRLRLLALAAAVLLGPAPEVCGALNVTVSPGPVVDYLEGENATLLC...
1705,"[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[1, 5, 7, 10, 18, 32, 33, 41, 42, 43, 45, 46, ...","[0.7850417122744976, 0.8815385633915113, 0.902...",MSRDVSLSPKSGDIRFNGTEPPVKVEVVDEEQSSLNNQLGFSTTLS...

In [11]:
import pandas as pd
import numpy as np
from sklearn.metrics import (
    f1_score, 
    roc_auc_score, 
    average_precision_score, 
    precision_score, 
    recall_score,
    matthews_corrcoef
)
import ast

def compute_residue_metrics(df, threshold=0.5, residues={'S', 'T', 'Y'}):
    """
    Computes classification metrics for S, T, and Y residues.
    
    Args:
        df (pd.DataFrame): DataFrame containing 'labels', 'sequence_indices', 'probs', and 'sequence'.
        threshold (float): Probability threshold for binary classification (default 0.5).
        
    Returns:
        pd.DataFrame: A DataFrame containing the computed metrics for each residue.
    """
    
    # Initialize dictionaries to aggregate data
    residue_data = { res : {'y_true': [], 'y_prob': []} for res in residues }
    # Iterate through the dataframe rows
    for index, row in df.iterrows():
        seq = row['sequence']
        
        # Handle potential string representations of lists if loaded from CSV
        labels = ast.literal_eval(row['labels']) if isinstance(row['labels'], str) else row['labels']
        indices = ast.literal_eval(row['sequence_indices']) if isinstance(row['sequence_indices'], str) else row['sequence_indices']
        probs = ast.literal_eval(row['probs']) if isinstance(row['probs'], str) else row['probs']
        
        # Aggregate true labels and probabilities by checking the residue at each index
        for label, idx, prob in zip(labels, indices, probs):
            residue = seq[int(idx)]
            if residue in residue_data:
                residue_data[residue]['y_true'].append(float(label))
                residue_data[residue]['y_prob'].append(float(prob))
                
    results = {}
    
    # Compute metrics for S, T, and Y
    for residue in residues:
        y_true = np.array(residue_data[residue]['y_true'])
        y_prob = np.array(residue_data[residue]['y_prob'])
        
        if len(y_true) == 0:
            # Handle cases where a residue might not appear in the dataset
            results[residue] = {m: np.nan for m in ['f1_score', 'auprc', 'auroc', 'precision', 'recall']}
            continue
            
        # Convert probabilities to binary predictions for F1, Precision, and Recall
        y_pred = (y_prob >= threshold).astype(int)
        
        # Handle AUROC/AUPRC calculation safely in case only one class is present in a batch
        try:
            auroc = roc_auc_score(y_true, y_prob)
        except ValueError:
            auroc = np.nan 
            
        try:
            auprc = average_precision_score(y_true, y_prob)
        except ValueError:
            auprc = np.nan

        results[residue] = {
            'f1_score': f1_score(y_true, y_pred),
            'auprc': auprc,
            'auroc': auroc,
            'precision': precision_score(y_true, y_pred),
            'recall': recall_score(y_true, y_pred),
            'mcc' : matthews_corrcoef(y_true, y_pred)
        }
        
    return results

In [12]:
compute_residue_metrics(preds)

{'T': {'f1_score': 0.4154852780806979,
  'auprc': 0.38877657775677077,
  'auroc': 0.7869861548011156,
  'precision': 0.38368580060422963,
  'recall': 0.4530321046373365,
  'mcc': 0.345133727942535},
 'S': {'f1_score': 0.5008523012132758,
  'auprc': 0.5123502684629222,
  'auroc': 0.8094591553133494,
  'precision': 0.43950725912890454,
  'recall': 0.5820999883463466,
  'mcc': 0.39555074611490343},
 'Y': {'f1_score': 0.23727230266230734,
  'auprc': 0.20159411051604006,
  'auroc': 0.7174137575102982,
  'precision': 0.25656565656565655,
  'recall': 0.2206776715899218,
  'mcc': 0.18798381602621336}}

In [ ]:
def compute_full_metrics(preds, threshold=0.5, label='STY'):
    y_true = []
    y_prob = []

    for _, row in preds.iterrows():
        y_true.extend(row['labels'])
        y_prob.extend(row['probs'])

    y_true, y_prob = np.asarray(y_true), np.asarray(y_prob)

    y_pred = (y_prob >= threshold).astype(int)

    try:
        auroc = roc_auc_score(y_true, y_prob)
    except ValueError:
        auroc = np.nan 
        
    try:
        auprc = average_precision_score(y_true, y_prob)
    except ValueError:
        auprc = np.nan

    results = {}
    results[label] = {
            'f1_score': f1_score(y_true, y_pred, zero_division=0),
            'auprc': auprc,
            'auroc': auroc,
            'precision': precision_score(y_true, y_pred, zero_division=0),
            'recall': recall_score(y_true, y_pred, zero_division=0),
            'mcc' : matthews_corrcoef(y_true, y_pred)
        }
    
    return results

In [ ]:
import os

def update_dict(dict1, dict2):
    for k, v in dict2.items():
        if not k in dict1:
            dict1[k] = v
        else:
            dict1[k] += v

def compute_metrics(log_folder, model_name,prot_info_path, splits_path, residues, n_folds=5):
    prot_info = pd.read_json(prot_info_path)
    per_residue_results = {}
    total_results = {}

    with open(splits_path, 'r') as f:
        splits = json.load(f)

    for fold in range(n_folds):
        path = os.path.join(log_folder, model_name, f'fold_{fold}', f'test_preds_fold_{fold}.json')
        prots = prot_info.iloc[splits[fold]['test']]
        preds = pd.read_json(path)
        preds['probs'] = preds['logits'].apply(lambda x: sigmoid(np.asarray(x)))

        # Assuming that the order of the prots is the same as preds
        preds['sequence'] = prots['sequence'].reset_index(drop=True)


        residue_metrics = compute_residue_metrics(preds, residues=residues)
        total_metrics = compute_full_metrics(preds, label="".join(residues))

        update_dict(per_residue_results, residue_metrics)
        update_dict(total_results, total_metrics)

    for buffer in (per_residue_results, total_results):
        for k, v in buffer.items():
            buffer[k] = v / n_folds

    print('Total metrics')
    print(total_results)

    print('Per Residue metrics')
    for r in residues:
        print(f'Residue {r}')
        print(per_residue_results[r])

In [78]:
compute_metrics(os.path.join('..', 'model', 'new_logs'), model, prot_info_path, splits_path, residues={'S', 'T', 'Y'})

TypeError: unsupported operand type(s) for +=: 'dict' and 'dict'